### ISSUE TITLE
ArborX is not compatible with ROCm 6.0

### ISSUE THREAD

**Issue by Rombur** [arborx/ArborX#1028]
ROCm  6.0 introduces roc-thrust 3.0 which is not compatible with the 2.x versions. At configuration time, we get an error that we cannot find a compatible version of roc-thrust because we are looking for roc-thrust 2.10.5 or newer https://github.com/arborx/ArborX/blob/59ec655a7468bd846e7ab635067fdffe1e0d56b0/CMakeLists.txt#L21
I am not sure that we need to have a minimal version requirement since ROCm 5.2 comes with roc-thrust 2.15

**Comment by aprokop** [comment]
> I am not sure that we need to have a minimal version requirement since ROCm 5.2 comes with roc-thrust 2.15

Agreed. The minimum version requirement was introduced in #434, back in ROCm 3.9 days. We can drop it.
