### ISSUE TITLE
Cryptic error for using ArborX when CUDA is not loaded

### ISSUE THREAD

**Issue by aprokop** [arborx/ArborX#118]
Situation:
- Kokkos is compiled with CUDA backend (with nvcc_wrapper)
- Arborx is compiled against that Kokkos and installed

If one tries to compile an example against ArborX installation, use `-DCMAKE_CXX_COMPILER="nvcc_wrapper"` but forgets to load/have nvcc in the path, the error is very cryptic:
```
CMake Error at /usr/share/cmake-3.10/Modules/FindMPI.cmake:970 (try_compile):
  Cannot copy output executable

    ''

  to destination specified by COPY_FILE:

    '<snip>/build/CMakeFiles/FindMPI/test_mpi_CXX.bin'

  Unable to find the executable at any of:

    <snip>/build/CMakeFiles/CMakeTmp/cmTC_7c7de
    <snip>/build/CMakeFiles/CMakeTmp/Debug/cmTC_7c7de
    <snip>/build/CMakeFiles/CMakeTmp/Development/cmTC_7c7de\
```
It is completely opaque. Does anyone has any ideas whether we can produce any helpful messages or diagnostics to help users understand what's going on?

**Comment by dalg24** [comment]
Sounds more like a Kokkos issue to me.

**Comment by Rombur** [comment]
I assume that you mean `-DCMAKE_CXX_COMPILER` and not `-DCMAKE_CXX_FLAGS`.  I agree that this a problem with Kokkos.

**Comment by aprokop** [comment]
But Kokkos does not use MPI, and this error may be only related to applications using Kokkos and MPI together.

**Comment by Rombur** [comment]
Would could try to compile a dummy code before calling `FindMPI` that would allow us to check that the compiler works/exists.

**Comment by dalg24** [comment]
> Would could try to compile a dummy code before calling `FindMPI` that would allow us to check that the compiler works/exists.

Doesn't CMake already run some checks on the compiler by default?

**Comment by aprokop** [comment]
Indeed it does:
```
-- The CXX compiler identification is unknown                       
-- Check for working CXX compiler: /home/xap/local/opt/kokkos/bin/nvcc_wrapper
-- Check for working CXX compiler: /home/xap/local/opt/kokkos/bin/nvcc_wrapper -- works
-- Detecting CXX compiler ABI info     
-- Detecting CXX compiler ABI info - failed                                                              
-- Found PkgConfig: /usr/bin/pkg-config (found version "0.29.1")
-- Found Kokkos: /home/xap/local/opt/kokkos/lib/libkokkos.a
CMake Error at /home/xap/local/opt/cmake-3.14.1/share/cmake-3.14/Modules/FindMPI.cmake:1188 (try_compile):
  Cannot copy output executable    
```

**Comment by sslattery** [comment]
isn't that a CMake `FindMPI` issue - not an nvcc wrapper issue? Are you guys adding MPI the new Make way with targets?

**Comment by aprokop** [comment]
The error was recorded here if we need look it up in the future. No actions were taken.
