### ISSUE TITLE
Test ArborX installation

### ISSUE THREAD

**Issue by aprokop** [arborx/ArborX#12]

**Comment by aprokop** [comment]
test

**Comment by aprokop** [comment]
test2

**Comment by aprokop** [comment]
We need further testing, as Tioga work uncovered a bunch of issues.
- Different languages
- Linking against a library that links against ArborX
- ...

**Comment by dalg24** [comment]
Having this dual build logic https://github.com/arborx/ArborX/blob/22eb4ebf889c92ad9c135f5c817f6ea06d4fba24/examples/bvh_driver/CMakeLists.txt#L1-L3
in all examples provided would be appropriate for testing.

**Comment by aprokop** [comment]
Now that #107 is merged, we should properly test it out. To make sure, I think we should:
- [ ] Update CMake in `examples/` to be run out of tree
- [ ] Copy the `examples/` in a different location during CI, and build against ArborX
