### ISSUE TITLE
ArborX/Kokkos initialize/finalize interaction

### ISSUE THREAD

**Issue by aprokop** [arborx/ArborX#127]
Kokkos has to be initialized prior to the first ArborX call. 
1. DTK has its own `DTK_init()`, `DTK_finalize()` calls, that support arguments `(argc, argv)`
2. `kokkos/fortran-interop` has C interface kokkos_initialize (inside a C++ file, calls Kokkos::initialize()), and a Fortran interface that binds to that.

As C/Fortran interface are not part of the kokkos/kokkos, and we don't want to depend on any extra repos, we have two alternatives:
- provide some init/finalize calls in ArborX
- Check for Kokkos initialization in the routines that interface with a user, and do initialization on the fly (no finalization, though...)

Opinions?

**Comment by dalg24** [comment]
Belongs to the `examples/` directory.  That would actually be a great addition.

**Comment by aprokop** [comment]
@dalg24 so you are for having users to write these calls on their own, and for ArborX not to provide them?

**Comment by dalg24** [comment]
Correct.  We provide just provide an example and make sure it works.

**Comment by sslattery** [comment]
I prefer this as well - ultimately having our own init functions proved to not work too well in other libraries like Cabana

**Comment by aprokop** [comment]
Reached consensus on not providing these calls.

**Comment by dalg24** [comment]
What about a fortran example?

**Comment by aprokop** [comment]
I spent some effort then, but it was quite painful, and I made little progress. I won't spend any more time on this until it becomes high priority.
