### ISSUE TITLE
Cannot build tests with PGI

### ISSUE THREAD

**Issue by Rombur** [arborx/ArborX#128]
I am trying to compile ArborX with PGI 19.4 but it doesn't work because Boost disables support for variadic macros for all the untested compilers. This means that `BOOST_TEST` is not supported when using PGI. Should we use `BOOST_CHECK` instead or say that we don't support PGI?

**Comment by dalg24** [comment]
What version of Boost did you try?

**Comment by Rombur** [comment]
I tried 1.67 but the code is the same in 1.71

**Comment by masterleinad** [comment]
Shouldn't https://github.com/boostorg/preprocessor/commit/b5c081bf7a2c043911a9048935c11a3e8d6c881a have addressed this? The commit should be in 1.71.0.

**Comment by Rombur** [comment]
Yeah you are right applying the patch fixes it

**Comment by aprokop** [comment]
So, PGI requires 1.71 and does not work with any of the older versions? Right now our requirement is 1.68 (I think). Should some CMake code be added to throw for this situation?

**Comment by Rombur** [comment]
The docker images uses 1.67 that's why I tried that. I think that it should work with 1.69. I don't know if we care enough about PGI to make CMake throw.

**Comment by aprokop** [comment]
I'd say we care enough to not fall into the same pitfall down the road. However, thinking about it, is it actually possible detect PGI build when using nvcc_wrapper?
