### ISSUE TITLE
Remove distances return argument

### ISSUE THREAD

**Issue by aprokop** [arborx/ArborX#141]
Pros:
- Sometimes it's convenient to have them

Cons:
- Distances can be easily computed in post-processing
- Code is complex as it has additional code branching
- We have to do square roots during search to keep track of them

**Comment by sslattery** [comment]
Is there enough work in the post-processing to warrant the extra kernel launch latency? It sounds like you may reduce divergence - so this could be a win?

**Comment by aprokop** [comment]
There should be enough work, as this will need to be computed for all pairs (query_index, result_index), traversing the full result graph.

**Comment by aprokop** [comment]
Removing from milestone, as this is unadvertised feature anyway, and we currently have no good solution to properly fix it.

**Comment by dalg24** [comment]
Obsolete no that we have callbacks
