### ISSUE TITLE
Improve sort

### ISSUE THREAD

**Issue by aprokop** [arborx/ArborX#145]
Note that this is different from #60, as that one concerns only scaling.

Here are some results from TIOGA (with CudaUVM). Three variants:
- Upstream master
- Using `unsigned int` for `size_type` template parameter in Kokkos' BinSort [[here](https://github.com/aprokop/ArborX/blob/dcc40adcc63f6bc253ec31f6050dd969f6e366c2/src/details/ArborX_DetailsSortUtils.hpp#L60)]
- Using Thrust [[here](https://github.com/aprokop/ArborX/blob/78f9a6f7b4d82b892e751a2ed9eefb0a101e3833/src/details/ArborX_DetailsSortUtils.hpp#L55)]
![mesh1_setup](https://user-images.githubusercontent.com/7297887/66701920-a1e47480-eccf-11e9-8187-0f9f1fe4124b.png)
![mesh1_search](https://user-images.githubusercontent.com/7297887/66701921-a6a92880-eccf-11e9-9603-f81a8e0da2df.png)
![mesh2_setup](https://user-images.githubusercontent.com/7297887/66701922-aad54600-eccf-11e9-8f86-c5621f8ba74f.png)
![mesh2_search](https://user-images.githubusercontent.com/7297887/66701924-af016380-eccf-11e9-829b-71d7847f21aa.png)

**Comment by aprokop** [comment]
We should also improve the OpenMP sort while we are at it. For example, omega_h [uses](https://github.com/SNLComputation/omega_h/blob/144a1c16b5f4c8dd66e55e8d43e9c37af0b5890b/src/Omega_h_sort.cpp#L50) [pss](https://github.com/wjakob/pss).

**Comment by aprokop** [comment]
Benchmark (my workstation) `--values=500000 --queries=200000`

`master`:
```
-----------------------------------------------------------------------------------------------------------------
Benchmark                                                                          Time           CPU Iterations
-----------------------------------------------------------------------------------------------------------------
BM_construction<ArborX::BVH<Cuda>>/500000/0/manual_time                         7647 us       7623 us         84
BM_knn_search<ArborX::BVH<Cuda>>/500000/200000/10/0/0/manual_time              59053 us      59214 us         12
BM_radius_search<ArborX::BVH<Cuda>>/500000/200000/10/0/0/0/manual_time         14999 us      15171 us         47
BM_construction<ArborX::BVH<CudaUVM>>/500000/0/manual_time                     14634 us      16615 us         48
BM_knn_search<ArborX::BVH<CudaUVM>>/500000/200000/10/0/0/manual_time           67977 us      68386 us         10
BM_radius_search<ArborX::BVH<CudaUVM>>/500000/200000/10/0/0/0/manual_time      18624 us      18840 us         38
```

`thrust`:
```
-----------------------------------------------------------------------------------------------------------------
Benchmark                                                                          Time           CPU Iterations
-----------------------------------------------------------------------------------------------------------------
BM_construction<ArborX::BVH<Cuda>>/500000/0/manual_time                         6744 us       6784 us         95
BM_knn_search<ArborX::BVH<Cuda>>/500000/200000/10/0/0/manual_time              59140 us      59304 us         11
BM_radius_search<ArborX::BVH<Cuda>>/500000/200000/10/0/0/0/manual_time         15083 us      15252 us         46
BM_construction<ArborX::BVH<CudaUVM>>/500000/0/manual_time                     13090 us      15064 us         51
BM_knn_search<ArborX::BVH<CudaUVM>>/500000/200000/10/0/0/manual_time           67731 us      68131 us         11
BM_radius_search<ArborX::BVH<CudaUVM>>/500000/200000/10/0/0/0/manual_time      18031 us      18249 us         39
```

**Comment by aprokop** [comment]
I guess the next step would be to rerun paper config to see the changes.

**Comment by dalg24** [comment]
Please next time run with `--benchmark_repetitions=X` and  `--benchmark_display_aggregates_only=false` and post mean, median, and standard deviation.

**Comment by aprokop** [comment]
@dalg24 Sorry, my bad. Will do the runs, and update the results. `--benchmark_display_aggregates_only` seems to be only in benchmark version 1.5.0, and not in 1.4.1 that I use.

**Comment by aprokop** [comment]
Updated the comment.

**Comment by aprokop** [comment]
Benchmark (my workstation), `hollow_box`-`hollow_sphere`

 `--values=500000 --queries=200000 --benchmark_repetitions=10 --benchmark_display_aggregates_only=false`

`master`:
```
BM_construction<ArborX::BVH<Cuda>>/500000/1/manual_time_mean                           9481 us         9630 us           10
BM_construction<ArborX::BVH<Cuda>>/500000/1/manual_time_median                         9435 us         9605 us           10
BM_construction<ArborX::BVH<Cuda>>/500000/1/manual_time_stddev                          143 us         78.9 us           10
BM_knn_search<ArborX::BVH<Cuda>>/500000/200000/10/1/3/manual_time_mean               112840 us       113001 us           10
BM_knn_search<ArborX::BVH<Cuda>>/500000/200000/10/1/3/manual_time_median             112787 us       112946 us           10
BM_knn_search<ArborX::BVH<Cuda>>/500000/200000/10/1/3/manual_time_stddev                188 us          189 us           10
BM_radius_search<ArborX::BVH<Cuda>>/500000/200000/10/0/1/3/manual_time_mean            5774 us         6068 us           10
BM_radius_search<ArborX::BVH<Cuda>>/500000/200000/10/0/1/3/manual_time_median          5762 us         6069 us           10
BM_radius_search<ArborX::BVH<Cuda>>/500000/200000/10/0/1/3/manual_time_stddev          45.8 us         8.47 us           10
BM_construction<ArborX::BVH<CudaUVM>>/500000/1/manual_time_mean                       18740 us        20743 us           10
BM_construction<ArborX::BVH<CudaUVM>>/500000/1/manual_time_median                     18786 us        20789 us           10
BM_construction<ArborX::BVH<CudaUVM>>/500000/1/manual_time_stddev                       204 us          204 us           10
BM_knn_search<ArborX::BVH<CudaUVM>>/500000/200000/10/1/3/manual_time_mean            122237 us       122652 us           10
BM_knn_search<ArborX::BVH<CudaUVM>>/500000/200000/10/1/3/manual_time_median          122177 us       122591 us           10
BM_knn_search<ArborX::BVH<CudaUVM>>/500000/200000/10/1/3/manual_time_stddev             305 us          306 us           10
BM_radius_search<ArborX::BVH<CudaUVM>>/500000/200000/10/0/1/3/manual_time_mean         9066 us         9253 us           10
BM_radius_search<ArborX::BVH<CudaUVM>>/500000/200000/10/0/1/3/manual_time_median       9063 us         9252 us           10
BM_radius_search<ArborX::BVH<CudaUVM>>/500000/200000/10/0/1/3/manual_time_stddev       50.0 us         50.0 us           10
```

`thrust`:
```
BM_construction<ArborX::BVH<Cuda>>/500000/1/manual_time_mean                           6521 us         6685 us           10
BM_construction<ArborX::BVH<Cuda>>/500000/1/manual_time_median                         6489 us         6660 us           10
BM_construction<ArborX::BVH<Cuda>>/500000/1/manual_time_stddev                         68.8 us         47.7 us           10
BM_knn_search<ArborX::BVH<Cuda>>/500000/200000/10/1/3/manual_time_mean               110895 us       111066 us           10
BM_knn_search<ArborX::BVH<Cuda>>/500000/200000/10/1/3/manual_time_median             110900 us       111068 us           10
BM_knn_search<ArborX::BVH<Cuda>>/500000/200000/10/1/3/manual_time_stddev                141 us          142 us           10
BM_radius_search<ArborX::BVH<Cuda>>/500000/200000/10/0/1/3/manual_time_mean            3856 us         4165 us           10
BM_radius_search<ArborX::BVH<Cuda>>/500000/200000/10/0/1/3/manual_time_median          3856 us         4163 us           10
BM_radius_search<ArborX::BVH<Cuda>>/500000/200000/10/0/1/3/manual_time_stddev          12.2 us         11.2 us           10
BM_construction<ArborX::BVH<CudaUVM>>/500000/1/manual_time_mean                       13643 us        15644 us           10
BM_construction<ArborX::BVH<CudaUVM>>/500000/1/manual_time_median                     13632 us        15632 us           10
BM_construction<ArborX::BVH<CudaUVM>>/500000/1/manual_time_stddev                      76.9 us         76.8 us           10
BM_knn_search<ArborX::BVH<CudaUVM>>/500000/200000/10/1/3/manual_time_mean            119367 us       119771 us           10
BM_knn_search<ArborX::BVH<CudaUVM>>/500000/200000/10/1/3/manual_time_median          119349 us       119762 us           10
BM_knn_search<ArborX::BVH<CudaUVM>>/500000/200000/10/1/3/manual_time_stddev             197 us          196 us           10
BM_radius_search<ArborX::BVH<CudaUVM>>/500000/200000/10/0/1/3/manual_time_mean         6374 us         6561 us           10
BM_radius_search<ArborX::BVH<CudaUVM>>/500000/200000/10/0/1/3/manual_time_median       6366 us         6552 us           10
BM_radius_search<ArborX::BVH<CudaUVM>>/500000/200000/10/0/1/3/manual_time_stddev       23.6 us         26.0 us           10

```

**Comment by aprokop** [comment]
Woah! For hollow variants, both construction and radius search dramatically benefit. For Cuda, hollow box construction is 32% faster, radius search is 34% faster. This is reminiscent of TIOGA results.

**Comment by aprokop** [comment]
I think we may want to design a checklist for accepting performance patches. Something like "Run the following benchmark configurations on these machines". I can write a script that will do this automatically so that it can be done with a push of a button.

**Comment by aprokop** [comment]
Of note, Thrust is part of CUDA Toolkit, an optional installation option of CUDA. A quick check showed that it is available on Summit (OLCF), Condo, and Cori (NERSC). Is that sufficient for us to not require a Thrust search through `find_package`?

**Comment by dalg24** [comment]
Is there a "standard" way of detecting it?
Also can you confirm we don't need any extra compile or link flag?

**Comment by aprokop** [comment]
> Is there a "standard" way of detecting it?

No.

>  Also can you confirm we don't need any extra compile or link flag?

Confirmed.

**Comment by aprokop** [comment]
Here are the results for #147 from Summit (same configuration as the one used for the paper).

# Filled box/filled ball
## Construction
![comparison_construction_filled_box](https://user-images.githubusercontent.com/7297887/66860702-b0df5700-ef5b-11e9-836b-b3033272d377.png)
## KNN
![comparison_knn_search_filled_box](https://user-images.githubusercontent.com/7297887/66860718-ba68bf00-ef5b-11e9-9b28-646aa2b56af6.png)
## Radius
![comparison_radius_search_filled_box](https://user-images.githubusercontent.com/7297887/66860763-c785ae00-ef5b-11e9-84e5-4b969a4fd58a.png)

# Hollow box/hollow ball
## Construction
![comparison_construction_hollow_box](https://user-images.githubusercontent.com/7297887/66860777-d0767f80-ef5b-11e9-95f7-6bed5d728094.png)
## KNN
![comparison_knn_search_hollow_box](https://user-images.githubusercontent.com/7297887/66860808-de2c0500-ef5b-11e9-9014-ca53a30ca033.png)
## Radius
![comparison_radius_search_hollow_box](https://user-images.githubusercontent.com/7297887/66860821-e5531300-ef5b-11e9-8e5b-15a033b71c0e.png)

**Comment by sslattery** [comment]
Wow - huge improvements for big problems. So this is just sorting by Morton index?

**Comment by aprokop** [comment]
@sslattery Yes, all the improvement is coming from the faster Morton index sorting, both for construction and search.

**Comment by aprokop** [comment]
Thrust sort was merged. The issue to remain open until we also fix OpenMP sort.

**Comment by masterleinad** [comment]
See https://github.com/kokkos/kokkos/issues/2914.

**Comment by aprokop** [comment]
In #267 we observed that sometimes BinSort is faster than Thrust. For example, in 100K case in bvh_driver it is 15% faster for filled box total construction time, and 25% faster for the shallow case. It means that the difference in the sort itself is even more dramatic. More investigation is required.

**Comment by aprokop** [comment]
I ran Cuda benchmark comparing Thrust vs BinSort for current master (760ae21). The results are mixed.
```
$ compare_bench.py benchmarks 202004160906_760ae21_master.json 202004160906_760ae21_master_nothrust.json | egrep '(median|CPU|------)'
Benchmark                                                                                           Time             CPU      Time Old      Time New       CPU Old       CPU New
--------------------------------------------------------------------------------------------------------------------------------------------------------------------------------
BM_construction<ArborX::BVH<Cuda>>/10000/0/manual_time_median                                    -0.0736         -0.0763          1646          1525          1658          1532
BM_construction<ArborX::BVH<Cuda>>/100000/0/manual_time_median                                   -0.3237         -0.2791          3323          2248          3661          2639
BM_construction<ArborX::BVH<Cuda>>/1000000/0/manual_time_median                                  +0.1931         +0.1539          8295          9897          8781         10133
BM_construction<ArborX::BVH<Cuda>>/10000/1/manual_time_median                                    -0.0231         -0.0334          1646          1608          1660          1604
BM_construction<ArborX::BVH<Cuda>>/100000/1/manual_time_median                                   -0.2194         -0.1917          3299          2575          3659          2958
BM_construction<ArborX::BVH<Cuda>>/1000000/1/manual_time_median                                  +0.3824         +0.3400          8295         11467          8775         11758
BM_knn_search<ArborX::BVH<Cuda>>/10000/10000/10/1/0/2/manual_time_median                         -0.0692         -0.0653          1452          1352          1542          1441
BM_knn_search<ArborX::BVH<Cuda>>/100000/100000/10/1/0/2/manual_time_median                       +0.0022         -0.0005         10547         10570         10996         10991
BM_knn_search<ArborX::BVH<Cuda>>/1000000/1000000/10/1/0/2/manual_time_median                     +0.0196         +0.0196         96112         97996         96973         98874
BM_knn_search<ArborX::BVH<Cuda>>/10000/10000/10/1/1/3/manual_time_median                         +0.0112         +0.0104          1609          1627          1698          1716
BM_knn_search<ArborX::BVH<Cuda>>/100000/100000/10/1/1/3/manual_time_median                       +0.0407         +0.0397         13755         14314         14171         14734
BM_knn_search<ArborX::BVH<Cuda>>/1000000/1000000/10/1/1/3/manual_time_median                     +0.0506         +0.0490        197212        207190        198075        207787
BM_radius_search<ArborX::BVH<Cuda>>/10000/10000/10/1/0/0/2/manual_time_median                    -0.0393         -0.0356          1113          1069          1203          1160
BM_radius_search<ArborX::BVH<Cuda>>/100000/100000/10/1/0/0/2/manual_time_median                  -0.0158         -0.0174          7212          7098          7652          7520
BM_radius_search<ArborX::BVH<Cuda>>/1000000/1000000/10/1/0/0/2/manual_time_median                +0.0659         +0.0660         60875         64889         61675         65749
BM_radius_search<ArborX::BVH<Cuda>>/10000/10000/10/1/0/1/3/manual_time_median                    +0.0192         +0.0174          1075          1096          1166          1186
BM_radius_search<ArborX::BVH<Cuda>>/100000/100000/10/1/0/1/3/manual_time_median                  -0.1156         -0.0996          3770          3334          4209          3790
BM_radius_search<ArborX::BVH<Cuda>>/1000000/1000000/10/1/0/1/3/manual_time_median                +0.9050         +0.8320         10350         19717         11172         20468
```

**Comment by aprokop** [comment]
I'd like to put a higher priority on figuring out our sort situation.

1. @dalg24 has been considering introducing a single interface following standard (presumably, `std::sort`
2. In #456, @masterleinad introduced a new overload for SYCL, that behaves different from Thrust overloads internally
3. Serial sort is slow
   I don't think it defaults to `std::sort`. I've tried running DBSCAN problem in serialwith 500,000 points with default sort, and `std::sort`, and the later one was dramatic improvement
   | Timer | BinSort | std::sort |
   | --- | --- | --- |
   | construction | 0.464 | 0.077 |
   | query+cluster | 1.607 | 1.218 |

The last point is relevant for the current ExaWind experiments: even though we don't sort queries, we still sort primitives.

**Comment by aprokop** [comment]
[Compadre](https://github.com/sandialabs/compadre) is working on integrating ArborX, replacing existing nanoflann version. They also hit an issue with the time taken by `Kokkos::BinSort` in the ArborX tree construction (it takes ~80% of overall time). `std::sort` for the same problem is about 3x faster.

Of note, Compadre uses Kokkos Threads backend. This is due to using the native install of the Apple Clang compiler (version 12), that does not configure with OpenMP backend. Specifically, it complains that the compiler was built without OpenMP support.

**Comment by masterleinad** [comment]
> Of note, Compadre uses Kokkos Threads backend. This is due to using the native install of the Apple Clang compiler (version 12), that does not configure with OpenMP backend. Specifically, it complains that the compiler was built without OpenMP support.

There is https://github.com/kokkos/kokkos/issues/3256 for that and https://github.com/kokkos/kokkos/pull/4105 might help.

**Comment by aprokop** [comment]
Closing in favor of Discussion, as there is no concrete action to take at this point.
