### ISSUE TITLE
Cannot compile CUDA tests with boost versions 1.68 - 1.74

### ISSUE THREAD

**Issue by aprokop** [arborx/ArborX#168]
Tried 1.69, 1.70, 1.71. All fail with 
```
../test/tstSequenceContainers.cpp(25): error: identifier "BOOST_TEST_TOOL_UNIV" is undefined
../test/tstSequenceContainers.cpp(25): error: identifier "BOOST_TEST_TOOL_UNIV_EX" is undefined
../test/tstSequenceContainers.cpp(25): error: identifier "CHECK" is undefined
../test/tstSequenceContainers.cpp(25): error: identifier "BOOST_TEST_INVOKE_IF_N_ARGS" is undefined
../test/tstSequenceContainers.cpp(89): error: identifier "BOOST_TEST_TOOL_UNIV" is undefined
../test/tstSequenceContainers.cpp(89): error: identifier "BOOST_TEST_TOOL_UNIV_EX" is undefined
../test/tstSequenceContainers.cpp(89): error: identifier "CHECK" is undefined
../test/tstSequenceContainers.cpp(89): error: identifier "BOOST_TEST_INVOKE_IF_N_ARGS" is undefined
```
1.68 works fine.

**Comment by masterleinad** [comment]
I see the same problem on `Summit`.

**Comment by dalg24** [comment]
> I see the same problem on `Summit`.

Does that mean upgrading Boost in the dev/ci container does not expose the problem?

**Comment by aprokop** [comment]
This seems to be a CUDA compilation issue. I tried the patch from [here](https://github.com/boostorg/preprocessor/commit/c436de6142477dd2c432e0836004c2503ef3b0f1) but that did not help.

**Comment by masterleinad** [comment]
Yes, I tried that as well before.

**Comment by aprokop** [comment]
1.72 does not work (was tested in #171 again).

**Comment by rpep** [comment]
Did you ever figure out the source of this error? I found the same issue on my own project which uses Boost Test, and compiling with the Intel Compiler on Windows + Linux.

**Comment by aprokop** [comment]
@rpep No. The patch proposed in the linked boost issue did not work for us. However, it worked for a different project so you may want to give it a try.

**Comment by aprokop** [comment]
Latest attempt with 1.73 in #332 failed.

**Comment by dalg24** [comment]
#332 was merged. We found that 1.74 is still not supported but 1.75 is.
