### ISSUE TITLE
Capture Use Case:  Distance to Wall

### ISSUE THREAD

**Issue by overfelt** [arborx/ArborX#201]
Just capturing the details of a use case at the request of ArborX developers, not a bug or feature request.  

I have an application where the distance from points in the volume to the nearest wall is required for a turbulence model.  One way we would like to calculate these values is to use ArborX to determine a few points on the surface that are closest to each point in the volume and then narrow the distance with a detailed calculation. This will be compared to a PDE based approach at scale and in parallel.  In any case, the ArborX approach could be used for an initial guess for a PDE solve which would then be used for the small update to the distance given small mesh motions.

**Comment by aprokop** [comment]
@overfelt Have you had a chance to give ArborX a try?

**Comment by aprokop** [comment]
No progress or action item in over 6 months, closing.
