### ISSUE TITLE
Allow buffer optimization with size zero

### ISSUE THREAD

**Issue by dalg24** [arborx/ArborX#205]
Weird use case a callback is used to get the results out and `insert()` never gets called.
The problem is this triggers the second pass which is totally unnecessary.

**Comment by aprokop** [comment]
Note that doing `buffer_size >= 0` in the https://github.com/arborx/ArborX/blob/2afac4e8b5ec7d84f2d12c528bad1767b1d75ad1/src/details/ArborX_DetailsBoundingVolumeHierarchyImpl.hpp#L376-L383 check fixes it, but not optimally, as it will still do the unnecessary `max` call.
