### ISSUE TITLE
Question about ArborX terminology

### ISSUE THREAD

**Issue by aprokop** [arborx/ArborX#210]
There is some ambiguity surrounding naming of things in ArborX. Specifically, the definitions of "query", "predicate" and "predicate with attachment".

My current understanding of those terms is:
* **predicate** is a boolean function operating on a leaf node/user provided geometry
* **query** is a function that given a predicate(s) returns the results satisfying them.

If this language is correct, than we should not use `Query` as an object and things like callbacks should read
```diff
-  template <typename Query, typename Insert>
-  KOKKOS_FUNCTION void operator()(Query const &, int index,
-                                  Insert const &insert) const;
+  template <typename Predicate, typename Insert>
+  KOKKOS_FUNCTION void operator()(Predicate const &, int index,
+                                  Insert const &insert) const;
```
On the other hand, the callback happens after predicate evaluated to true on that node, so what is exactly the object here?

There is also a question of whether "predicate with attachment" should be considered different concept from "predicate".

**Comment by dalg24** [comment]
> what is exactly the object here?

It is literally the predicate.
Another option would be to pass to the callback the query index and the attached data if any.

**Comment by aprokop** [comment]
> It is literally the predicate.

Well, not exactly. As the predicate was already evaluated for this node, it is no longer the boolean function in the callback context. Instead, it is something else.

>  Another option would be to pass to the callback the query index and the attached data if any.

Again, is this the right terminology? What is a `query index` if the query is defined as above? Should this be `predicate index`? It is quite confusing.

**Comment by dalg24** [comment]
> Well, not exactly. As the predicate was already evaluated for this node, it is no longer the boolean function in the callback context. Instead, it is something else.

It is the predicate Andrey.

> Again, is this the right terminology? What is a `query index` if the query is defined as above? Should this be `predicate index`? It is quite confusing.

Sure "predicate index".  It is the `index` in `ArborX::Traits::Access<UserCustomTypeOrKokkosView>::get(custom_or_view, index);` that returned the predicate that was satisfied, where `custom_or_view` was passed as 1st argument to `BVH::query()`.
