### ISSUE TITLE
Make ArborX work with current Trilinos/Kokkos install

### ISSUE THREAD

**Issue by aprokop** [arborx/ArborX#224]
After Kokkos package was updated in Trilinos, we can no longer build ArborX against it. For example,
```
/home/xap/local/opt/trilinos-kokkos/include/OpenMP/Kokkos_OpenMP_Exec.hpp:51:2: error: #error "You enabled Kokkos OpenMP support without enabling OpenMP in t
he compiler!"
```

It seems that the code was restructured/modified. Some of the flags that used to be in `trilinos/lib/pkgconfig/kokkos.ps` (like `-fopenmp;--std=c++11`) were moved elsewhere (`trilinos/lib/cmake/Kokkos/KokkosConfig.cmake`). There is no `kokkos_generated_settings.cmake` anymore, either.

**Comment by aprokop** [comment]
Asked Kokkos developers about it in kokkos/kokkos#2779.

**Comment by aprokop** [comment]
The Kokkos PR was merged in Kokkos develop. Waiting for it to appear in Trilinos.

**Comment by masterleinad** [comment]
This will be part of the `Kokkos` 3.1 release. There is no plan to hotfix it before.
