### ISSUE TITLE
Fix Boost warnings

### ISSUE THREAD

**Issue by aprokop** [arborx/ArborX#23]
Currently, I'm getting a bunch of warnings like this:
[boost_warnings.txt](https://github.com/arborx/ArborX/files/3122676/boost_warnings.txt)

I wonder it that happens because we include some files (like `ArborX_BoostRTreeHelpers.hpp`) which have `<boost/*>` includes directly into other ArborX files, without making use of corresponding Boost targets (which, I think, would set the proper `SYSTEM`).

**Comment by dalg24** [comment]
@aprokop are you still seeing this issue?

**Comment by aprokop** [comment]
Yes. Here are some examples:
```
/home/xap/local/opt/spack/opt/spack/linux-ubuntu18.04-x86_64/gcc-7.3.0/boost-1.68.0-j2mqoxflxrkb5c27hqgzp3yer5aepbtp/include/boost/get_pointer.hpp:48:46: warning: 'template<class> class std::auto_ptr' is deprecated [-Wdeprecated-declarations]
/home/xap/local/opt/spack/opt/spack/linux-ubuntu18.04-x86_64/gcc-7.3.0/boost-1.68.0-j2mqoxflxrkb5c27hqgzp3yer5aepbtp/include/boost/mpl/set/aux_/item.hpp:47:70: warning: friend declaration 'char (& boost::mpl::operator||(const boost::mpl::s_item<T, Base>&, boost::mpl::aux::type_wrapper<T>*))[boost::mpl::s_item<T, Base>::order:: value]' declares a non-template function [-Wnon-template-friend]
```

**Comment by dalg24** [comment]
Please share your compile command (`make VERBOSE=1`)

**Comment by aprokop** [comment]
This is the log file of `ninja -v`: [make.log](https://github.com/arborx/ArborX/files/3652431/make.log).

**Comment by masterleinad** [comment]
> `/home/xap/local/opt/spack/opt/spack/linux-ubuntu18.04-x86_64/gcc-7.3.0/boost-1.68.0-j2mqoxflxrkb5c27hqgzp3yer5aepbtp/include/boost/get_pointer.hpp:48:46: warning: 'template<class> class std::auto_ptr' is deprecated [-Wdeprecated-declarations]`

You could define `BOOST_NO _AUTO_PTR` for this one.

The other one, I am seeing when compiling deal.II all the time, too. I have not found any other solution then simply suppressing it.

**Comment by dalg24** [comment]
This is weird, I don't see the path to your Spack install on the compile line.  If you look at the builds on Jenkins, we do use `-isystem` for Boost headers.

**Comment by aprokop** [comment]
@dalg24 I have spack modules loaded. They modified `LD_LIBRARY_PATH` and `CPATH`, so you won't see the spack install path. (Not sure if this is what you are asking).

**Comment by dalg24** [comment]
Directories in `CPATH` will be included with the `-I` option.  See [doc](https://gcc.gnu.org/onlinedocs/cpp/Environment-Variables.html).

**Comment by aprokop** [comment]
Some more [info](https://gitlab.kitware.com/cmake/cmake/issues/19291). I don't like the option of not loading spack modules and specifying them explicitly. This also does not solve the gcc warnings.

However, in the link that @dalg24, there is a solution:
```shell
$ export CPLUS_INCLUDE_PATH=$CPATH
```
This results in no warnings for me.
