### ISSUE TITLE
Inspect copies between host and device

### ISSUE THREAD

**Issue by masterleinad** [arborx/ArborX#230]
Running `nvprof` shows
```
Time(%) Time     Calls Avg       Min       Max      Name
11.39%  821.00ms 217   3.7834ms  1.4080us  108.56ms [CUDA memcpy HtoD]
10.96%  790.22ms 389   2.0314ms  1.5360us  101.28ms [CUDA memcpy DtoH]
```
We need to investigate where all these copies come from.

**Comment by dalg24** [comment]
Running what?

**Comment by aprokop** [comment]
> Running what?

Standard distributed benchmark with 10^6 values and queries on fetnat.

**Comment by dalg24** [comment]
This hardly answer the question...

**Comment by dalg24** [comment]
There are 3 difference benchmarks (construction, kNN, radius search).  The driver performs a number of iteration that we don't really have control over.

**Comment by masterleinad** [comment]
```
nvprof --print-gpu-summary ./ArborX_DistributedTree.exe --queries=1000000 --values=1000000 --neighbors=20
```

**Comment by masterleinad** [comment]
> There are 3 difference benchmarks (construction, kNN, radius search). The driver performs a number of iteration that we don't really have control over.

Sure. This is a reminder to look into this a bit closer.

**Comment by dalg24** [comment]
What are the columns?

**Comment by masterleinad** [comment]
I updated the description.

**Comment by aprokop** [comment]
> The driver performs a number of iteration that we don't really have control over.

Not sure what you mean. This is *distributed* benchmark, not on-node, so there is no Google benchmark. Everything (construction, both searches) is executed once.

**Comment by dalg24** [comment]
I missed the "distributed" part...

**Comment by masterleinad** [comment]
With
```
nvprof --print-gpu-trace ./ArborX_BoundingVolumeHierarchy.exe --benchmark_repetitions=1 --benchmark_filter=Cuda
```
I see 1732 occurrences of memcpy with bvh_driver. 

I get 413 for `benchmark_filter="BM_knn_search<ArborX::BVH<Cuda>` and 644 for `benchmark_filter="BM_radius_search<ArborX::BVH<Cuda>` and 331 for `benchmark_filter="BM_construction<ArborX::BVH<Cuda>`. Increasing the number of values to 1e6 gives 439 occurrences for knn, using 1e6 additionally gives 55 occurences (also with the default value for values). The same number for radius search are 119 and 139.

**Comment by aprokop** [comment]
Construction
```
$ nvprof --print-gpu-summary ./ArborX_DistributedTree.exe \
    --do-not-perform-knn-search --do-not-perform-radius-search 2>cuda-summary.log
$ egrep '(DtoH|HtoD)' cuda-summary.log
```
results in
```
Time(%)      Time     Calls       Avg       Min       Max  Name
 12.43%  117.95us        20  5.8970us     672ns  102.69us  [CUDA memcpy HtoD]
  2.02%  19.169us        20     958ns     800ns  1.7930us  [CUDA memcpy DtoH]
```
which seems reasonable. Running `--print-gpu-trace` indicates just a
handful of copies for each kernel launch.

"construction+knn"   : 135 HtoD and 252 DtoH.
"construction+radius":  67 HtoD and 110 DtoH.
```
Size  Throughput  SrcMemType  DstMemType   Name

   -           -           -           -  _ZN6Kokkos4Impl33cuda_parallel_launch_local_memoryINS0_11ParallelForIZN6ArborX7Details25DistributedSearchTreeImplINS_6DeviceINS_4CudaENS_9CudaSpaceEEEE22communicateResultsBackINS_4ViewIPNS_4pairIiiEEJS9_EEEEEvP19ompi_communicator_tRT_NSC_IPiJS9_EEERSM_SN_PNSC_IPdJS9_EEEEUliE_NS_11RangePolicyIJS7_EEES7_EEEEvT_ [775]
128B  131.54MB/s      Device    Pageable  [CUDA memcpy DtoH]
128B  146.72MB/s    Pageable      Device  [CUDA memcpy HtoD]
128B  152.59MB/s      Device    Pageable  [CUDA memcpy DtoH]
128B  131.54MB/s      Device    Pageable  [CUDA memcpy DtoH]
128B  119.21MB/s    Pageable      Device  [CUDA memcpy HtoD]
128B  152.59MB/s      Device    Pageable  [CUDA memcpy DtoH]
128B  152.59MB/s      Device    Pageable  [CUDA memcpy DtoH]
128B  146.72MB/s    Pageable      Device  [CUDA memcpy HtoD]
128B  158.95MB/s      Device    Pageable  [CUDA memcpy DtoH]
128B  152.59MB/s      Device    Pageable  [CUDA memcpy DtoH]
62MB  9.9748GB/s      Device    Pageable  [CUDA memcpy DtoH]
128B  115.60MB/s      Device    Pageable  [CUDA memcpy DtoH]
62MB  10.351GB/s    Pageable      Device  [CUDA memcpy HtoD]
128B  108.99MB/s      Device    Pageable  [CUDA memcpy DtoH]
81MB  10.709GB/s      Device    Pageable  [CUDA memcpy DtoH]
128B  119.21MB/s      Device    Pageable  [CUDA memcpy DtoH]
81MB  10.667GB/s    Pageable      Device  [CUDA memcpy HtoD]
128B  108.99MB/s      Device    Pageable  [CUDA memcpy DtoH]
81MB  10.513GB/s      Device    Pageable  [CUDA memcpy DtoH]
128B  100.39MB/s      Device    Pageable  [CUDA memcpy DtoH]
81MB  8.6087GB/s    Pageable      Device  [CUDA memcpy HtoD]
128B  9.3269MB/s      Device    Pageable  [CUDA memcpy DtoH]
128B  127.16MB/s    Pageable      Device  [CUDA memcpy HtoD]
   -           -           -           -  void Kokkos::Impl::cuda_parallel_launch_local_memory<Kokkos::Impl::ParallelFor<Kokkos::Impl::ViewValueFunctor<Kokkos::Cuda, int, bool=1>, Kokkos::RangePolicy<>, Kokkos::Cuda>>(Kokkos::Cuda) [831]
```
I think this indicates that we enter the `communicateResultsBack`, did
a bunch of copieds, and launched a parallel_for (which should probably
be "fill_buffer". (Note: I don't see createFromSends, though. Was it inlined?)

A bunch of slower copies are 128B. Is it a view size? I wonder why it
would have been copied back to host, though...

If I just look at the construction, there are 34 128B calls, each
taking 600-1200 nanoseconds, and there is only a single HtoD call that is more than a few bytes and taking more than a single microsecond.

Overall, I did not see anything outstanding. I think most of the copies are coming from copying views metadata to and from the device, and from some 4B copies of `lastElement()` things.

I'd like to know a bit more about how kernels are launched, and how the `KOKKOS_LAMBDA` captures things, and what is the magic 128B number corresponds to. But that's for later.
