### ISSUE TITLE
Header-only install [question]

### ISSUE THREAD

**Issue by jrobbin** [arborx/ArborX#245]
Is it possible to do a header-only install of ArborX via spack?  I'd like to use ArborX in an existing project by adding something like:
```
depends_on('arborx~mpi~serial~cuda' when='+arborx')
```
to my project's spack package.py file, then add:
```cmake
find_package(ArborX REQUIRED)
```
to my project's CMakeLists.txt file.  I was able to do so by modifying the CMakeLists.txt in ArborX and the package.py for ArborX in spack (diffs shown below), but I'd prefer to use ArborX as is.  

Thanks!
Josh

Changes to ArborX's package.py in spack:
```diff
diff --git a/var/spack/repos/builtin/packages/arborx/package.py b/var/spack/repos/builtin/packages/arborx/package.py
index 45e368884..d63504561 100644
--- a/var/spack/repos/builtin/packages/arborx/package.py
+++ b/var/spack/repos/builtin/packages/arborx/package.py
@@ -36,15 +36,21 @@ class Arborx(CMakePackage):
         spec = self.spec
 
         options = [
-            '-DCMAKE_PREFIX_PATH=%s' % spec['kokkos'].prefix,
             '-DARBORX_ENABLE_TESTS=OFF',
             '-DARBORX_ENABLE_EXAMPLES=OFF',
             '-DARBORX_ENABLE_BENCHMARKS=OFF',
             '-DARBORX_ENABLE_MPI=%s' % ('ON' if '+mpi' in spec else 'OFF')
         ]
 
-        if '+cuda' in spec:
+        if '+cuda' in spec or '+serial' in spec or '+openmp' in spec:
+            '-DCMAKE_PREFIX_PATH=%s' % spec['kokkos'].prefix,
             nvcc_wrapper_path = spec['kokkos'].prefix.bin.nvcc_wrapper
             options.append('-DCMAKE_CXX_COMPILER=%s' % nvcc_wrapper_path)
+        else:
+            options.append('-DARBORX_ENABLE_HEADERONLY=ON')
 
         return options
+
+    def setup_environment(self, spack_env, run_env):
+        run_env.prepend_path('CPATH', join_path(self.prefix, 'include', 'details'))
```

Changes to ArborX:
```diff
diff --git a/CMakeLists.txt b/CMakeLists.txt
index 2ed5176..6530242 100644
--- a/CMakeLists.txt
+++ b/CMakeLists.txt
@@ -1,17 +1,22 @@
 cmake_minimum_required(VERSION 3.12)
 project(ArborX CXX)
 
-find_package(Kokkos 3.0 QUIET)
-if(NOT Kokkos_FOUND)
-  set(CMAKE_MODULE_PATH ${CMAKE_SOURCE_DIR}/cmake ${CMAKE_MODULE_PATH})
-  find_package(Kokkos 3.0 REQUIRED)
-endif()
-if(Kokkos_ENABLE_CUDA)
-  kokkos_check(OPTIONS CUDA_LAMBDA)
+if(NOT ARBORX_ENABLE_HEADERONLY)
+  set(ARBORX_ENABLE_KOKKOS ON)
+  find_package(Kokkos 3.0 QUIET)
+  if(NOT Kokkos_FOUND)
+    set(CMAKE_MODULE_PATH ${CMAKE_SOURCE_DIR}/cmake ${CMAKE_MODULE_PATH})
+    find_package(Kokkos 3.0 REQUIRED)
+  endif()
+  if(Kokkos_ENABLE_CUDA)
+    kokkos_check(OPTIONS CUDA_LAMBDA)
+  endif()
 endif()
 
 add_library(ArborX INTERFACE)
-target_link_libraries(ArborX INTERFACE Kokkos::kokkos)
+if(ARBORX_ENABLE_KOKKOS)
+  target_link_libraries(ArborX INTERFACE Kokkos::kokkos)
+endif()
 set_target_properties(ArborX PROPERTIES INTERFACE_COMPILE_FEATURES cxx_std_14)
 
 option(ARBORX_ENABLE_MPI "Enable MPI support" OFF)
@@ -75,11 +80,19 @@ configure_package_config_file(cmake/ArborXConfig.cmake.in
   ${CMAKE_CURRENT_BINARY_DIR}/ArborXConfig.cmake
   INSTALL_DESTINATION lib/cmake/ArborX
 )
-install(FILES
-  ${CMAKE_CURRENT_BINARY_DIR}/ArborXConfig.cmake
-  ${CMAKE_CURRENT_SOURCE_DIR}/cmake/FindKokkos.cmake
-  ${CMAKE_CURRENT_BINARY_DIR}/ArborXSettings.cmake
-  DESTINATION lib/cmake/ArborX )
+
+if(ARBORX_ENABLE_KOKKOS)
+  install(FILES
+    ${CMAKE_CURRENT_BINARY_DIR}/ArborXConfig.cmake
+    ${CMAKE_CURRENT_SOURCE_DIR}/cmake/FindKokkos.cmake
+    ${CMAKE_CURRENT_BINARY_DIR}/ArborXSettings.cmake
+    DESTINATION lib/cmake/ArborX )
+else()
+  install(FILES
+    ${CMAKE_CURRENT_BINARY_DIR}/ArborXConfig.cmake
+    ${CMAKE_CURRENT_BINARY_DIR}/ArborXSettings.cmake
+    DESTINATION lib/cmake/ArborX )
+endif()
 
 if(ARBORX_ENABLE_MPI)
   install(DIRECTORY ${PROJECT_SOURCE_DIR}/src/ DESTINATION include
diff --git a/cmake/ArborXConfig.cmake.in b/cmake/ArborXConfig.cmake.in
index 231573e..1442dc0 100644
--- a/cmake/ArborXConfig.cmake.in
+++ b/cmake/ArborXConfig.cmake.in
@@ -2,8 +2,10 @@
 
 set(CMAKE_MODULE_PATH ${CMAKE_CURRENT_LIST_DIR} ${CMAKE_MODULE_PATH})
 
-include(CMakeFindDependencyMacro)
-find_dependency(Kokkos)
+if(ARBORX_ENABLE_KOKKOS)
+  include(CMakeFindDependencyMacro)
+  find_dependency(Kokkos)
+endif()
 
 include("${CMAKE_CURRENT_LIST_DIR}/ArborXSettings.cmake")
 if(ARBORX_ENABLE_MPI)
```

**Comment by aprokop** [comment]
@jrobbin ArborX is already header-only, and the installation will only contain headers. What you seem to suggest to do is to disable all Kokkos backends. Can you please elaborate on what you are trying to achieve? Are you trying to make the installed version of ArborX with a version of Kokkos that you provide post-install?

**Comment by jrobbin** [comment]
@aprokop Thanks for your prompt response.  That's correct.  I'd like to provide Kokkos post-install.  With the modifications in my post above, spack doesn't try to install kokkos for me.   My project depends on trilinos, so that's where I'm getting kokkos, but spack doesn't recognize that the kokkos dependency is fulfilled by trilinos, so it wants to install kokkos for me.

**Comment by aprokop** [comment]
OK, so it seems that what you really want is to be able to build ArborX against Trilinos installation containing Kokkos, and possibly use `spack` to do that. Right?

We have an application depending on ArborX that also requires this functionality. There are several challenges to that. First of all, even if we assume for a moment that we merge you changes, it won't work right now as ArborX already depends on Kokkos 3.0 and the required fixes in Kokkos to make ArborX work with Trilinos/Kokkos will only land in Kokkos 3.1, which has not been released yet.

Once Kokkos 3.1 lands in Trilinos `devel`, it should be possible for a standalone build of ArborX to be used against Trilinos/Kokkos. Updating ArborX' spack package would be the next step. I cannot give a timeline right now as it depends on others, but it is a high priority for us.

Are there particular versions of Trilinos or Kokkos that you depend on? If you can tolerate Trilinos prior to Kokkos 3.0 landing there, we can find an older hash in ArborX that allows it to be built against that Trilinos (though, not through Spack, and it needs an additional patch with `-std=c++14` flags).

Sorry for the long reply, I wish we had a simple solution.

**Comment by jrobbin** [comment]
That's correct.  I'm building a project that uses trilinos 12.18.1 (which I think maps to Kokkos 2.9) and uses VOTD of ArborX via spack using the modifications above.  I'm going to redo my build process to make sure that I haven't somehow deceived myself, but I think I'm using the master branch of ArborX with Trilinos 12.18.1 and it's working for me (it builds and passes unit tests).  Perhaps I'm using a subset of capability in ArborX that doesn't need the latest Kokkos?  Here's a link to my code in a feature branch:

https://github.com/platoengine/platoanalyze/blob/meshmap/src/Plato_MeshMap.hpp

**Comment by aprokop** [comment]
> Perhaps I'm using a subset of capability in ArborX that doesn't need the latest Kokkos?

I thought for a moment and realized that we depend on the *build system* of 3.0, but not on the API so much. So your patch will likely still work with the latest Kokkos.

**Comment by jrobbin** [comment]
I'll use these patches until things settle out with the newer version of kokkos then.  Thanks!

**Comment by aprokop** [comment]
@jrobbin Thank you for submitting this issue! This suggested an approach we haven't thought about. We will consider it further to see if it is feasible in the long term.

**Comment by jrobbin** [comment]
You're welcome!  I'll keep an eye on the ArborX repo to see if this approach is added.

**Comment by jrobbin** [comment]
@aprokop I've implemented the above as a temporary work around.  Just in case you want to try it out:
```
git clone https://github.com/platoengine/spack.git
source spack/share/spack/setup-env.sh
spack install arborx~mpi~cuda~serial @header_only
```
(As we established yesterday, 'header_only' may be a bit of a misnomer.)
