### ISSUE TITLE
Output views in BVH::query() should not be required to be templated on device type

### ISSUE THREAD

**Issue by dalg24** [arborx/ArborX#270]
```C++
ArborX::BVH<MemorySpace> bvh{...};

Kokkos::View<int*, ExecutionSpace> indices("indices", 0);
Kokkos::View<int*, ExecutionSpace> offset("offset", 0);
//                 ^^^^ not a device type
bvh.query(..., indices, offset); // <-- This currently won't compile but it should
```

Related to #269

**Comment by dalg24** [comment]
@aprokop I fail to see how this would qualify as a bug

**Comment by aprokop** [comment]
For me, this is something that we expected to work, but it does not. The semantics were that you pass indices and offsets as views. The way those views were declared affected the semantics, so I think it's a bug.

**Comment by dalg24** [comment]
It never did work because we never thought one would want to use it this way.

**Comment by aprokop** [comment]
I understand that. But again, the expectation I had that any view should work.
