### ISSUE TITLE
Arborx::Sphere support + different kind of geometry for nodes/leaves

### ISSUE THREAD

**Issue by JulienLoiseau** [arborx/ArborX#292]
I am working on SPH simulations using ArborX.
This requires to use particles represented by a sphere and the interactions are between sphere-sphere. 

For now in ArborX, the following is not currently possible: 

```
  std::vector<ArborX::Sphere> ents; 
  ArborX::BVH<Kokkos::HostSpace> bvh{Kokkos::DefaultHostExecutionSpace{},
      ents};
```

The type must decay to ArborX::Box or ArborX::Point.
My understanding is the whole tree structure is based on the same geometry (nodes+leaves) and boxes are way faster for the searches than spheres. 

In my case all my objects are spheres, so I would need to transform them into boxes and then refine the search afterwise to see the ones falling into this sphere-sphere interaction. 

Would it be possible to: 
- Add support for sphere natively in the tree (sphere-sphere interaction might increase the number of interactions during the traversal but are fast to compute) 
- Have different types of geometry for the nodes and the leaves in the tree? They could also be both specified by the user? 

Thank you.

**Comment by aprokop** [comment]
One way to do this is to write access traits to get `Box` out of spheres (no explicit transformation necessary), and add (unadvertised) callbacks to do fine search (i.e, intersection sphere-sphere).

**Comment by dalg24** [comment]
Elaborating on what Andrey replied, this is how you would currently achieve that
```C++
  template <>
  struct Access<std::vector<Sphere>, PrimitivesTag>
  {
    static std::size_t size(std::vector<Sphere> const &v) { return v.size(); }
    static Box get(std::vector<Sphere> const &v, std::size_t i)
    {
      auto const &c = v[i].centroid();
      auto const &r = v[i].radius();
      return {Point{c[0] - r, c[1] - r, c[2] - r},
              Point{c[0] + r, c[1] + r, c[2] + r}};
    }
    using memory_space = Kokkos::HostSpace;
  };
  } // namespace Traits
  } // namespace ArborX

   struct CustomCallback
  {
    std::vector<ArborX::Sphere> primitives_;
    template <typename Predicate, typename OutputFunctor>
    void operator()(Predicate const &predicate, int i,
                    OutputFunctor const &out) const
    {
      // Assuming that your predicate geometries are boxes below
      // because ArborX::Details::intersects() is missing overloads at the moment
      ArborX::Box const &b = getGeometry(predicate);
      ArborX::Sphere const &s = primitives_[i];
      if (ArborX::Details::intersects(s, b))
        out(i);
    }
  };
```

**Comment by aprokop** [comment]
@JulienLoiseau Have you had a chance to try the approach suggested by @dalg24?
