### ISSUE TITLE
Specify minimum boost version for benchmark

### ISSUE THREAD

**Issue by aprokop** [arborx/ArborX#311]
On cades, it picked up 1.53 by default, which just does not compile:
```
/home/xap/code/arborx-paper/test/ArborX_BoostRTreeHelpers.hpp:41:36: error: ‘index’ in namespace ‘boost::geometry’ does not name a type
 using Parameter = boost::geometry::index::linear<16>;
```
But the configure stage passes as we don't check it (we only check min version for tests).

Need to figure out what's the minimum version and add that.

**Comment by aprokop** [comment]
The minimum Boost version containing Boost.Geometry index is 1.54.

**Comment by masterleinad** [comment]
Don't we check that we have at least 1.69 in https://github.com/arborx/ArborX/blob/27c4f9c04e32d99c97c0d9eca6583de3bed8c769/test/CMakeLists.txt#L27-L35?

**Comment by aprokop** [comment]
@masterleinad The version is checked only in `tests/`, not in `benchmark`. But both include `ArborX_BoostRTreeHelpers.hpp`, where this error is coming from.
