### ISSUE TITLE
Fix warning in access_traits_host example

### ISSUE THREAD

**Issue by aprokop** [arborx/ArborX#313]
```
../examples/access_traits/example_host_access_traits.cpp(48): here

../src/details/ArborX_DetailsTreeConstruction.hpp(240): warning: calling a __host__ function("std::vector< ::ArborX::Point, ::std::allocator< ::ArborX::Point> > ::vector") from a __host__ __device__ function("") is not allowed
```
We never see them in CI due to #272. I'm not sure what's the best to fix it. Probably move away from using `std::vector`. Removing `KOKKOS_FUNCTION` would not work as `Access::get` is called from such a function.

**Comment by dalg24** [comment]
Well either we remove that example when CUDA is enabled or we keep on looking the other way.

**Comment by aprokop** [comment]
What is the thinking behind using `std::vector` in the example? With that, one is only able to construct the hierarchy, but not even query it as we need `Kokkos::View` for that.

**Comment by dalg24** [comment]
> What is the thinking behind using `std::vector` in the example?

The motivation was to provide another example of access traits that does not require CUDA.

> With that, one is only able to construct the hierarchy, but not even query it as we need `Kokkos::View` for that.

You need views for `{offset, indices}`, sure.
