### ISSUE TITLE
Document that the lifetime of the DistributedSearchTree should be within MPI initialization region

### ISSUE THREAD

**Issue by aprokop** [arborx/ArborX#346]
In #135 we introduced duplicating of user-provided communicators to cleanly separate the library's communication from that of the user. We store the duplicated communicator inside `ArborX::DistributedSearchTree`. However, what we did not realize was that it can lead to the problem in the following situation:
```c++
MPI_Initialize(argc, argv);
ArborX::DistributedSearchTree<DeviceType> tree(comm, primitives);
tree.query(...);
MPI_Finalize();
```
The issue is that the destructor for the distributed tree, which contains `MPI_comm_free(&_comm);` will be called **after** `MPI_Finalize()`.

There is currently nothing in the interface to indicate that it cannot/should not be used this way. After searching online, I cannot say definitively what `MPI_Finalize()` does with non-freed communicators. But as it cleans up all MPI context, I think the proper fix would be to check if MPI is still initialized before freeing the communicator.

Reported-by: @mattbement

**Comment by dalg24** [comment]
This is not a defect.  This is expected.  The MPI execution environment, just like the Kokkos one, needs to be properly initialized before you create our distributed tree data structure and these are not be finalized as long as any object is in scope.
