### ISSUE TITLE
Replace ViewAllocateWithoutInitializing with view_alloc

### ISSUE THREAD

**Issue by aprokop** [arborx/ArborX#363]
`Kokkos::ViewAllocateWithoutInitializing` could be deprecated soon. While there is no reason to rush things with this change, changing all instances of its use in ArborX to `Kokkos::view_alloc(label, Kokkos::WithoutInitializing)` is easy to do and there is no downside to being proactive in .

**Comment by dalg24** [comment]
For reference see https://github.com/kokkos/kokkos/pull/3264

**Comment by aprokop** [comment]
@dalg24 What is the recommended order of the arguments to `view_alloc`? Is it `view_alloc(label, WithoutInitializing)` or reverse?

**Comment by dalg24** [comment]
I like `view_alloc(WithoutInitializing, label)` but it does not really matter.

**Comment by aprokop** [comment]
> I like `view_alloc(WithoutInitializing, label)` but it does not really matter.

That's funny, I like the opposite :) But agreed.

**Comment by aprokop** [comment]
This is on hold until/if free functions to create views become available. See [this](https://github.com/arborx/ArborX/pull/390#issuecomment-700182637) comment.
