### ISSUE TITLE
Double free when making copies of a distributed tree

### ISSUE THREAD

**Issue by dalg24** [arborx/ArborX#368]
This occurred to me when reviewing ECP-copa/Cabana#295
The implicitly-declared copy constructor and copy assignment operator are problematic because they make copies of the communicator data member and when an object gets out of scope `MPI_Comm_free` gets called on it.
https://github.com/arborx/ArborX/blob/4834bff44c23c9510c6ed93366638dcdf85ab217/src/ArborX_DistributedSearchTree.hpp#L45

**Comment by aprokop** [comment]
This is not the only problem from copying communicators. If a user copies a distributed tree, then the MPI calls and requests from different trees may overlap resulting in undefined behavior.

The fix is straightforward: copy constructor and copy assignment operators must duplicated the communicator.

**Comment by masterleinad** [comment]
Time for `https://clang.llvm.org/extra/clang-tidy/checks/cppcoreguidelines-special-member-functions.html`?

**Comment by aprokop** [comment]
> Time for `https://clang.llvm.org/extra/clang-tidy/checks/cppcoreguidelines-special-member-functions.html`?

Good suggestion, but maybe overkill for now.

**Comment by masterleinad** [comment]
Why overkill? Isn't thinking about copy/move semantics worth it?

**Comment by aprokop** [comment]
@masterleinad Probably not. I would rather not get distracted by possibly multiple places to get spotted by the tool at the moment. But it could be interesting to just post the results of it here just to see where we are at.
