### ISSUE TITLE
Document minimum versions for CMake and Boost

### ISSUE THREAD

**Issue by masterleinad** [arborx/ArborX#37]
Since we are using imported targets with `Boost`, we need to be careful to maintain compatibility (https://stackoverflow.com/questions/42123509/cmake-finds-boost-but-the-imported-targets-not-available-for-boost-version). In particular, there needs to be some kind of discussion in the installation instructions.

**Comment by aprokop** [comment]
Should probably be addressed in #140.

**Comment by aprokop** [comment]
Decided not to mention this in installation instructions, but keep an eye on this.
