### ISSUE TITLE
Resolve HIP tester failures

### ISSUE THREAD

**Issue by aprokop** [arborx/ArborX#373]
The `HIP-3.5` CI tests fail in what seems random manner. It is always `ArborX_LinearBVH_Test` test that may fail. This really slows down the pull request processing, and requires many `retest this please`. I think it's time to do one of the following:
- actually figure out what's going on there
- update to 3.7 to see if it helps
- disable HIP testing

**Comment by dalg24** [comment]
How frequent are these failures?  I consider "do nothing" to be a reasonable option.  I would object to disabling but I'm fine with the ROCm upgrade even though I don't see how this would help.

**Comment by masterleinad** [comment]
The `HIP` CI test is not required and we can merge pull requests without it.

**Comment by aprokop** [comment]
Documenting HIP failures:
```
<snip>
/var/jenkins/workspace/ArborX_PR-369/test/tstLinearBVH.cpp(834): error: in "structured_grid<Kokkos__Device<Kokkos__Experimental__HIP_ Kokkos__Experimental__HIPSpace>>": check indices_host(i) == i has failed [1059 != 1056]
/var/jenkins/workspace/ArborX_PR-369/test/tstLinearBVH.cpp(834): error: in "structured_grid<Kokkos__Device<Kokkos__Experimental__HIP_ Kokkos__Experimental__HIPSpace>>": check indices_host(i) == i has failed [1060 != 1057]
/var/jenkins/workspace/ArborX_PR-369/test/tstLinearBVH.cpp(835): error: in "structured_grid<Kokkos__Device<Kokkos__Experimental__HIP_ Kokkos__Experimental__HIPSpace>>": check offset_host(i) == i has failed [1056 != 1057]
<snip>
```
Are we sure it's not a bug in Kokkos HIP implementation? If it is intermittent failure, and the failure is slightly off indices, does not that indicate that there is some kind of race condition (in `parallel_scan` from what it seems) that may produce wrong answer?

**Comment by aprokop** [comment]
> The `HIP` CI test is not required and we can merge pull requests without it.

@masterleinad While true, failing HIP test also bypasses the style checks, which are required.

**Comment by masterleinad** [comment]
What I meant is that we can currently merge pull requests even if CI is failing. Of course, bypassing the style checks is problematic then.
Locally the test is passing with Kokkos 3.2 and HIP 3.6. for me. Let's see if simply updating `Kokkos` helps.

**Comment by aprokop** [comment]
The problem is not getting any better. Do we expect anything to change anytime soon, or do we just continue merging PRs with failing HIP in foreseeable future?

**Comment by masterleinad** [comment]
> The problem is not getting any better. Do we expect anything to change anytime soon, or do we just continue merging PRs with failing HIP in foreseeable future?

HIP-3.8. fixed a bunch of things. So it might be worth trying that. Unfortunately, I can not reproduce the issue manually on other machines so we don't have a good test case. Still, I think it's important to keep testing with HIP to see if more issues come up.

**Comment by aprokop** [comment]
Closing with the merge of #392. Reopen as needed.
