### ISSUE TITLE
Deprecate legacy access traits

### ISSUE THREAD

**Issue by dalg24** [arborx/ArborX#399]
Cross referencing platoengine/platoanalyze#2

We should consider emitting deprecation warnings https://github.com/arborx/ArborX/blob/2263411aa962cd00b4ea31ab3001db1c6ab00d5b/src/details/ArborX_AccessTraits.hpp#L179-L186

I had not marked it at the time because we are testing that the old traits are still valid and I didn't want to deal with warnings.

**Comment by aprokop** [comment]
Our compilation test for legacy access traits breaks on Ascent with gcc/11.2 and cuda/11.4.2. It also breaks on Perlmutter with nvhpc. Unclear whether we want to maintain that. It has been two years since we introduced that.

We could rip it out, and replace it with an error message.

**Comment by rgayatri23** [comment]
I ran into the same issue on Perlmutter with cuda/11.5 and gcc/11.2
