### ISSUE TITLE
Create Spack package

### ISSUE THREAD

**Issue by aprokop** [arborx/ArborX#4]
Dependencies:
- CMake 3.13+
- Kokkos: 2.7.00+

Not sure about the minimum version of Kokkos that we can work with.

**Comment by aprokop** [comment]
Here is a draft. Comments?

```python
from spack import *


class Arborx(CMakePackage):
    """ArborX is a performance-portable library for geometric search"""

    homepage = "http://github.com/arborx/arborx"
    git      = "https://github.com/arborx/arborx.git"

    version('master', branch='master')

    variant('cuda', default=False, description='enable Cuda backend')
    variant('openmp', default=False, description='enable OpenMP backend')
    variant('serial', default=True, description='enable Serial backend (default)')
    variant('mpi', default=True, description='enable MPI')

    depends_on('cmake@3.12:')
    depends_on('cuda', when='+cuda')
    depends_on('mpi', when='+mpi')

    # ArborX relies on Kokkos to provide devices, thus having one-to-one match
    # The only way to disable those devices is to make sure Kokkos does not
    # provide them
    depends_on('kokkos@2.7.00:+cuda+enable_lambda', when='+cuda')
    depends_on('kokkos@2.7.00:~cuda', when='~cuda')
    depends_on('kokkos@2.7.00:+openmp', when='+openmp')
    depends_on('kokkos@2.7.00:~openmp', when='~openmp')
    depends_on('kokkos@2.7.00:+serial', when='+serial')
    depends_on('kokkos@2.7.00:~serial', when='~serial')

    def cmake_args(self):
        spec = self.spec

        options = [
            '-DCMAKE_PREFIX_PATH=%s' % (spec['kokkos'].prefix),
            '-DArborX_ENABLE_TESTS=OFF',
            '-DArborX_ENABLE_EXAMPLES=OFF'
        ]

        if '+cuda' in spec:
            options.extend([
                '-DCMAKE_CXX_COMPILER=%s' % (spec['kokkos'].prefix.bin+"/nvcc_wrapper")
            ])

        return options
```

**Comment by dalg24** [comment]
* Are we guaranteed `mvcc_wrapper` is present in the Kokkos installed via Spack?
* We need to open issue to make MPI actually be an optional dependency

**Comment by aprokop** [comment]
> Are we guaranteed `nvcc_wrapper` is present in the Kokkos installed via Spack?

I checked and it's there.

> We need to open issue to make MPI actually be an optional dependency

Agreed.

**Comment by Rombur** [comment]
I would remove `depends_on('cuda', when='+cuda')` since we only depend on cuda through kokkos

**Comment by aprokop** [comment]
> I would remove `depends_on('cuda', when='+cuda')` since we only depend on cuda through kokkos

Without that it fails with 
```
  >> 31    CMake Error at /home/xap/local/opt/spack-develop/opt/spack/linux-ubuntu18.04-x86_64/gcc-7.3.0/cmake-3.14.1-bw67sallsm2yaq6pytl62gajaybq7v7l/share/cmake-3.14/Modules/FindMPI.cmake:
           1188 (try_compile):
     32      Cannot copy output executable
     33    
     34        ''
     35    
     36      to destination specified by COPY_FILE:
     37    
```
during configuration.

**Comment by Rombur** [comment]
Oh that's the error I saw on when I was configuring without cuda but I had the compiler set to `nvcc_wrapper`

**Comment by aprokop** [comment]
> Oh that's the error I saw on when I was configuring without cuda but I had the compiler set to `nvcc_wrapper`

I have it set to `nvcc_wrapper` to for `+cuda` variant. Are you saying that we should not do that while wanting cuda?

**Comment by aprokop** [comment]
@dalg24 If ArborX is header only, there is nothing device specific in `include/`. Is there anything specifying the devices in `lib/cmake`? I.e., can installed ArborX be used with any device? If yes, than we don't need `openmp`, `serial`, and `cuda` variants.

**Comment by dalg24** [comment]
> Is there anything specifying the devices in `lib/cmake`?

There should not.  Have you checked?

**Comment by aprokop** [comment]
Actually, nevermind, we cannot remove those variants as we need to make sure that our kokkos dependency has them.

**Comment by aprokop** [comment]
@Rombur 
Ping on this:
> I have it set to `nvcc_wrapper` too for `+cuda` variant. Are you saying that we should not do that while wanting cuda?

**Comment by Rombur** [comment]
No, I am just saying that it's the error I've seen before when I was configuring without cuda but I had the compiler set to `nvcc_wrapper`. I don't know how spack deals with `nvcc_wrapper`

**Comment by aprokop** [comment]
OK, it's almost ready. I updated the MPI dependency to turn on/off `ArborX_ENABLE_MPI`. The only other minor nitpicking thing is this block:
```python
    depends_on('kokkos@2.7.00:+cuda+enable_lambda', when='+cuda')
    depends_on('kokkos@2.7.00:~cuda', when='~cuda')
    depends_on('kokkos@2.7.00:+openmp', when='+openmp')
    depends_on('kokkos@2.7.00:~openmp', when='~openmp')
    depends_on('kokkos@2.7.00:+serial', when='+serial')
    depends_on('kokkos@2.7.00:~serial', when='~serial')
```
What I don't really like is that we disable kokkos variants. But the only workaround that would be to keep track of device types on the ArborX side, which we should not do.

**Comment by aprokop** [comment]
The PR is in progress (intentionally not cross-linked): PR 11474 at spack/spack.

**Comment by aprokop** [comment]
Upstream PR was merged.
