### ISSUE TITLE
Question: Parallel DBSCAN

### ISSUE THREAD

**Issue by pedro-ricardo** [arborx/ArborX#405]
Hello there,

I'm searching for a scalable parallel algorithm of DBSCAN using MPI. I had some dificulties with the documentation of this library to find stuff ... Do you have it?

**Comment by aprokop** [comment]
@pedro-ricardo Thanks for asking! So far, we have only implemented the on-node version of DBSCAN (PR #331), as there was not much interest in the MPI version as of yet. But this is something I keep in the back on my mind to work on once I have time.

**Comment by pedro-ricardo** [comment]
Hello there, thanks for the quick response.
Sorry to say that but it's nothing about cosmology.

We work with large temporal datasets with lots of columns obtained from industrial processes. 

All the implementations I found so far were falty in some of way for my purpose. Be it by not dealing with lots of columns, having problems with SpeedUp or not being in some low level language like  C, C++ or Fortran.

That `dbscan` tag that your library has lead me to here. And it seemed better organized :+1: 

But thanks anyway!
