### ISSUE TITLE
Feature proposal: allow early termination of traversal

### ISSUE THREAD

**Issue by aprokop** [arborx/ArborX#407]
# Motivation

There are some algorithms that could benefit from being able to stop early:
- Detecting core points in DBSCAN
  This is similar to counting the number of neighbors, but can stop early, as soon as `min_pts` number of neighbors reached, as at that threshold we already know that it is a core point. Given  that it may be feasible to use `min_pts = 5`, while the true number of neighbors is in hundreds or thousands, this has a lot of benefit.
- Algorithms in class of "find first of the objects satisfying something"
  It also includes a subclass of algorithms where it is known a priori that there is a single object satisfying the condition. For example, searching for an element of a mesh a point belongs to.

Some applications potentially benefiting:
- HACC (through DBSCAN)
- ExaWind (through finding element in a mesh a point belongs to)

This only makes sense for spatial search.

# Ideas

The desired features of any approach implementing the feature:
1. If a user does not use it, he does not pay for it
2. If a user does not use it, he does not need to implement it
3. If a user uses it, it should be straightforward.

One approach could be changing the callback signature to return `bool` (instead of `void`) indicating whether the traversal should continue. However, it breaks 2) as now all callbacks have to explicitly return `true` even if they don't use the feature.

**Comment by aprokop** [comment]
Some data for computing core points using HACC data.

Time to count all neighbors: 0.433

min_pts - stop counting and terminate after count reaches this threshold value

| min_pts | Time | Speedup |
| -: | -- |:--:|
| 1 | 0.062 | 7.0x |
| 2 | 0.075 | 5.8x|
| 5 | 0.082 | 5.3x|
| 10 | 0.099 | 4.4x|
| 25 | 0.144 | 3.0x |
| 50 | 0.176 | 2.5x|
| 100 | 0.228 | 1.9x|
| 500 | 0.381 | 1.1x | 
| 1000 | 0.429| 1.0x|

**Comment by dalg24** [comment]
I would use something strongly typed instead of a boolean and not require from users to change the signature if they don't use it.

**Comment by aprokop** [comment]
@dalg24 could you elaborate and/or provide pseudocode?

**Comment by aprokop** [comment]
Potentially, the scope of this proposal may be expanded to "determine the type of callback provided and act accordingly". For example, callbacks may be:
- Standard (implemented) callbacks
- Callbacks controlling execution
  - Early termination (this proposal)
  - Child choice (which child should be followed first?)
- Callbacks called at different execution points
  - Internal nodes vs leaf nodes

**Comment by aprokop** [comment]
Fixed by #427.
