### ISSUE TITLE
roc::rocprim_hip target not found when using HIP compiler 3.8 with rocThrust

### ISSUE THREAD

**Issue by wspear** [arborx/ArborX#433]
I'm testing out ArborX with a Kokkos built with the HIP compiler.

Kokkos was built like:
module load rocm/3.8.0 # or newer
git clone -b develop https://github.com/kokkos/kokkos.git
cd kokkos
mkdir build
cd build
cmake -DKokkos_ARCH_VEGA906=on -DCMAKE_CXX_COMPILER=hipcc \
-DKokkos_ENABLE_HIP=on -DKokkos_ENABLE_SERIAL=on \
-DKokkos_ENABLE_TESTS=on \
-DKokkos_ENABLE_HIP_RELOCATABLE_DEVICE_CODE=off \
..
make -j 8 # or `nproc`

When I try to run cmake for ArborX like:

 cmake    -D CMAKE_INSTALL_PREFIX=../install     -D ARBORX_ENABLE_MPI=ON  -D ARBORX_ENABLE_TESTS=ON      -D CMAKE_CXX_COMPILER=hipcc     -D CMAKE_CXX_EXTENSIONS=OFF  -D CMAKE_PREFIX_PATH=../install ..

I get numerous errors like:
CMake Error at test/CMakeLists.txt:53 (add_executable):
  Target "ArborX_Miscellaneous.exe" links to target "roc::rocprim_hip" but
  the target was not found.  Perhaps a find_package() call is missing for an
  IMPORTED target, or an ALIAS target is missing?

Thanks to @aprokop who correctly suggested that adding -D ARBORX_ENABLE_ROCTHRUST=OFF would work around this issue.

**Comment by dalg24** [comment]
This is a defect on the rocThrust that is fixed from version 3.9

**Comment by aprokop** [comment]
Some of the things we found out in #432 is that this is an issue only with rocm < 3.9.

**Comment by dalg24** [comment]
We have two options, either some variant of the workaround suggested in #432 or try to set the 3.9 requirement.  I haven't verified if rocThrust correctly export their version though.

**Comment by wspear** [comment]
In case it matters, though it seems this Kokkos was built with HIP 3.8, it looks like the HIP used to build ArborX resulting in this error was version: 3.9.20412-6d111f85

**Comment by dalg24** [comment]
what rocThrust was found?

**Comment by wspear** [comment]
False alarm. 3.8 in the container where the work was happening.

**Comment by aprokop** [comment]
Decided to only allow rocthrust for >= 3.9. @wspear Thanks for reporting!
