### ISSUE TITLE
Figure out inline issues

### ISSUE THREAD

**Issue by aprokop** [arborx/ArborX#454]
I'm running DBSCAN benchmark with 100K points using gcc/7.5.0 on the host (Intel Xeon CPU E5-2620 v4 2.10GHz).

The current `master` flamegraph ([flame.svg.txt](https://github.com/arborx/ArborX/files/5788289/flame.svg.txt)) has stacks containing `ArborX::Point::operator[]`, which was expected to be inlined:
![Screen Shot 2021-01-08 at 11 35 03 AM](https://user-images.githubusercontent.com/7297887/104040429-a1be7780-51a5-11eb-9156-fd60a135bc6f.png)

If I change all `KOKKOS_INLINE_FUNCTION` to `KOKKOS_FORCEINLINE_FUNCTION` in `Point` files, it disappears ([flame-forceinline.svg.txt](https://github.com/arborx/ArborX/files/5788297/flame-forceinline.svg.txt))
 
![Screen Shot 2021-01-08 at 11 36 41 AM](https://user-images.githubusercontent.com/7297887/104040577-cf0b2580-51a5-11eb-9226-7b6447d1c7c5.png)
and the traversal is sped up by 15-20%. 

If I go further, and change a bunch of inline functions to force inline in Point, Box, Sphere, distance, and a bunch of other files, I obtained 33% faster runtime.

This does not seem to be the case for CUDA, though. Introducing force inline (at least, in `Point`) did not seem to change runtime. And I don't have a flame graph for it.

We need to better understand the situation, and how to fix it.

P.S. To produce flame graph, execute this:
```bash
perf record -g ./ArborX_DBSCAN.exe --cluster-min-size=100 --binary --eps 0.042 --filename hacc_points.dat --core-min-size 1 --print-dbscan-timers 
perf script | $FLAMEGRAPH_DIR/stackcollapse-perf.pl | $FLAMEGRAPH_DIR/flamegraph.pl > flame.svg
```
assuming you downloaded [FlameGraph](https://github.com/brendangregg/FlameGraph) into `$FLAMEGRAPH_DIR`. The resulting file, `flame.svg`, can be opened in Firefox for examination.

**Comment by Rombur** [comment]
> We need to better understand the situation, and how to fix it.

Seems to me that this is a valid case to use `KOKKOS_FORCEINLINE_FUNCTION`. We probably want to check on other benchmarks to verify this result but I don't see what we need to understand better.

**Comment by aprokop** [comment]
User error, wrong CMake build type (CMake silently ignored it), which resulted in it building unoptimized code. With proper one, flame graph is actually much better, and **everything** in the tree traversal is inlined: 
[flame-opt.svg.txt](https://github.com/arborx/ArborX/files/5788534/flame-opt.svg.txt): 
![Screen Shot 2021-01-08 at 12 25 19 PM](https://user-images.githubusercontent.com/7297887/104045472-9cb0f680-51ac-11eb-8340-555f0fb9b0f2.png)
