### ISSUE TITLE
Set properties on unit tests

### ISSUE THREAD

**Issue by dalg24** [arborx/ArborX#50]
Slave machines used in automated testing get wildly oversubscribed, especially when allowing a number of concurrent builds >1
* [ ] Consider specifying how many processors a given unit test require
* [ ] Must act on MPI unit tests that have OpenMPI enabled (set `OMP_NUM_THREADS` environment variable and specify the number of MPI processes instead of using `MPIEXEC_MAX_NUMPROCS`)

**Comment by aprokop** [comment]
Since #296 this hasn't been an issue, and there are no plans to act on this. Closing.
