### ISSUE TITLE
Address timeout issues for PGI and SYCL builds

### ISSUE THREAD

**Issue by aprokop** [arborx/ArborX#507]
Two tests periodically time out in these two builds:
- `DistributedTreeTest`
- `QueryTest`

It's unclear to me what the best way to address this is. We could go through all the tests, and try to reduce all sizes by half, for example. But I looked through the distributed tree, and the sizes are already smallish (like 100 points per rank). So it may be just the number of tests times, somehow, as both builds have only 1-2 backends.

**Comment by masterleinad** [comment]
I would not be surprised if the `JIT` compiler for `SYCL` just struggles with the number of kernels to be compiled for `QueryTest`. Splitting this into multiple executables might help.

**Comment by dalg24** [comment]
What about keeping just one exe but adding several tests with filters?

**Comment by aprokop** [comment]
> What about keeping just one exe but adding several tests with filters?

This sounds like a good idea. The only concern I have is making sure that all tests run. I'm not sure how to guarantee this automatically, without manually keeping things in sync.

**Comment by dalg24** [comment]
> > What about keeping just one exe but adding several tests with filters?
> 
> This sounds like a good idea. The only concern I have is making sure that all tests run. I'm not sure how to guarantee this automatically, without manually keeping things in sync.

Should be safe to use a combination of include/exclude filters
```
<exe> --run_test=+<a>
<exe> --run_test=+<b>
<exe> --run_test=!<a>:<b>

**Comment by aprokop** [comment]
#511 seems to have fixed SYCL timeouts. HIP still time outs periodically, but not too often.
