### ISSUE TITLE
Get rid of `printf` guarding with SYCL

### ISSUE THREAD

**Issue by dalg24** [arborx/ArborX#613]
Related to kokkos/kokkos#4634

When we will upgrade the our requirements/CI base image, we should be able to get rid of our guarding `printf` statements in device code in `examples/` such as
https://github.com/arborx/ArborX/blob/a1b1a0000c641326910205975538657674f947ae/examples/callback/example_callback.cpp#L60-L62

This is to remind us to fix.

**Comment by aprokop** [comment]
What is the "recent" version of the SYCL compiler? I did not see it in the linked issue.

**Comment by masterleinad** [comment]
`Kokkos` is now using the latest release ~December but `20210903` is also fine. We just need to see what the deprecation warnings in the compiler look like.
