### ISSUE TITLE
Gitlab CI environment needs update

### ISSUE THREAD

**Issue by aprokop** [arborx/ArborX#634]
```
Ascent's OS was upgraded to RHEL 8 on February 11.  We strongly recommend
  rebuilding prior to running on upgraded system.
```
Besides updating the modules
```diff
--- a/.gitlab-ci.yml
+++ b/.gitlab-ci.yml
@@ -11,7 +11,8 @@ stages:

 .LoadModules:
   before_script:
-    - module load gcc/7.4.0 cuda/10.1.243 cmake/3.18.2 git/2.20.1 spectrum-mpi/10.3.1.2-20200121
+    - module load gcc/7.5.0 cuda/10.1.243 cmake/3.22.2 git/2.31.1 spectrum-mpi/10.4.0.3-20210112
+      module list

 .BuildBoost:
   extends: .LoadModules
```
we also need to rebuild all the dependencies.

**Comment by aprokop** [comment]
The benchmarks still not running because of things like
```
warning: failed to remove arborx-master/build_master/CMakeFiles/CMakeTmp/.nfs000000000561312d00001424: Device or resource busy
Error encountered during job: exit status 1
Error encountered during job: Error executing run_exec: exit status 1
```
I recall that on of the ways to work around the timeouts on some HPC systems was to add `--debug-trycompile` flag.

**Comment by masterleinad** [comment]
> The benchmarks still not running because of things like

I would say "doesn't run anymore". It certainly was running for some time after fixing it.

> I recall that on of the ways to work around the timeouts on some HPC systems was to add --debug-trycompile flag.

We can try if that helps but otherwise, I don't really have a good idea.

**Comment by aprokop** [comment]
Maybe we would also need to manually wipe out the build directories on Arcticus prior to testing a patch with `--debug-trycompile`.
