### ISSUE TITLE
[Question] Incorrect and differing results when conducting a fixed-radius search on GPU (works on CPU)

### ISSUE THREAD

**Issue by mschmidt271** [arborx/ArborX#645]
Hello all. I have written some code to do a fixed-radius search using ArborX, and I've got things working great on CPU for serial/OpenMP. However, swapping over to GPU, I am getting incorrect answers that differ from run to run, and I would guess the problem is probably that I'm a relative newbie to Kokkos. I'll include the guts of my code below and note that I use the `AccessTraits` structs and `PointCloud`/`Spheres` found in [example_cuda_access_traits.cpp](https://github.com/arborx/ArborX/blob/master/examples/access_traits/example_cuda_access_traits.cpp) verbatim. Also, let me know if there's a better way to get in contact, and I'll happily get rid of the issue.

Thank you!

```c++
using ExecutionSpace = Kokkos::DefaultExecutionSpace;
using MemorySpace = ExecutionSpace::memory_space;

[...]

auto fx = Kokkos::subview(fX, 0, Kokkos::ALL());
auto fy = Kokkos::subview(fX, 1, Kokkos::ALL());
auto fz = Kokkos::subview(fX, 2, Kokkos::ALL());

ArborX::BVH<MemorySpace> bvh{ExecutionSpace{}, PointCloud{&fx(), &fy(), &fz(), xlen}};
Kokkos::View<int*, MemorySpace> offsets("offsets", 0);
Kokkos::View<int*, MemorySpace> indices("indices", 0);
ArborX::query(bvh, ExecutionSpace{}, Spheres{&fx(), &fy(), &fz(), &frad(), xlen}, indices, offsets);
```

**Comment by aprokop** [comment]
You should not take the addresses of the subviews. You take them on host, and then they get copied to the device. So I think it accesses random data when running on the device. In the access traits example, the pointers are [already on the device](https://github.com/arborx/ArborX/blob/81f013e38ef52fc36a847b2cc52f22ecb17dbd4d/examples/access_traits/example_cuda_access_traits.cpp?rgh-link-date=2022-03-02T20%3A05%3A57Z#L76-L78).

> Also, let me know if there's a better way to get in contact, and I'll happily get rid of the issue.

The GitHub issues is the best way.

**Comment by dalg24** [comment]
`&fx()` is a bug in your code.  It does not compile with the Kokkos `develop` branch (since https://github.com/kokkos/kokkos/pull/4799) and it makes (possibly wrong) assumptions about the `fX` rank-2 view layout (we can't tell from the code you posted).
I suspect if you did `fx.data()` and you made sure that `fX` was layout right your code would work but you probably should be writing you own custom `Spheres` structure and access traits.

**Comment by mschmidt271** [comment]
After chatting with @dalg24 on the kokkos slack channel a bit, I got my issue worked out! I'll include basic details of the new code below for posterity and close the issue. Thanks, all!

```c++
template <class MemorySpace>
struct Spheres
{
  Kokkos::View<float**, MemorySpace> points;
  float radius;
};
template <class MemorySpace>
struct ArborX::AccessTraits<Spheres<MemorySpace>, ArborX::PredicatesTag> {
  using memory_space = MemorySpace;
  using size_type = std::size_t;
  static KOKKOS_FUNCTION size_type size(Spheres<MemorySpace> const& x) {
    return x.points.extent(0);
  }
  static KOKKOS_FUNCTION auto get(Spheres<MemorySpace> const& x, size_type i) {
    return ArborX::attach(
        ArborX::intersects(ArborX::Sphere{
            ArborX::Point{x.points(i, 0), x.points(i, 1), x.points(i, 2)},
            x.radius}),
        (int)i);
  }
};

int main(int argc, char* argv[]) {

[...]

auto fX = Kokkos::View<float*[3], Kokkos::LayoutRight, MemorySpace>("float X", xlen);

[...]

ArborX::BVH<MemorySpace> bvh{ExecutionSpace(), fX};
ArborX::query(bvh, ExecutionSpace{}, Spheres<MemorySpace>{fX, fradius}, indices, offsets);
```
