### ISSUE TITLE
Tested compilers in jenkins

### ISSUE THREAD

**Issue by Rombur** [arborx/ArborX#68]
I have tried to find all the compilers we would want to use in Jenkins. We probably just want to test a subset of the list

Compiler | Serial | OpenMP | CUDA | OpenMP/CUDA
-- | -- | -- | -- | --
Clang-CUDA: clang 7 + cuda 9.2 |   |   | X |  
NVCC: 10.1 gcc 7.4 |   |   |   | X
GCC: 5.4 (oldest compiler with C++14 support) | X |   |   |  
GCC: 9.1 (latest compiler) | X |   |   |  
Intel 2019 |   | X |   |  
XL (need access to Power) |   |   |   | X
PGI: 19.4  |   |   |   | X

**Comment by masterleinad** [comment]
I don't think supporting `XL` is feasible at all. You get internal compiler errors all over the place.

**Comment by masterleinad** [comment]
The same holds for `PGI`.

**Comment by masterleinad** [comment]
`Intel 18.0` seems to work with `Serial`.

**Comment by Rombur** [comment]
> The same holds for PGI.

I really doubt that's true. I compiled DTK with PGI 6 months ago but you need the special touch... PGI has 2 different backends, so you need to pass a flag to use their llvm backend

**Comment by Rombur** [comment]
> I don't think supporting XL is feasible at all.

Strange I was able to compile deal.II with XL but you need to "right" version of XL...

**Comment by masterleinad** [comment]
OK. Apart from not linking in `Kokkos` properly, I again get a bunch of
```
"BOOST_TEST_INVOKE_IF_N_ARGS" is undefined
"BOOST_TEST_TOOL_UNIV" is undefined
identifier "BOOST_TEST_INVOKE_IF_N_ARGS" is undefined
identifier "BOOST_TEST_TOOL_UNIV" is undefined
identifier "BOOST_TEST_TOOL_UNIV_EX" is undefined
identifier "CHECK" is undefined
```
with `PGI` (without `CUDA`).

**Comment by aprokop** [comment]
We added PGI recently. Can we close this now?

**Comment by Rombur** [comment]
Maybe we could still add Intel compiler (for Aurora)

**Comment by masterleinad** [comment]
...and a compiler for `HIP`.

**Comment by aprokop** [comment]
HIP compiler was added to testing. There is no priority to test with Intel. Closing.
