### ISSUE TITLE
Add testing with DataTransferKit

### ISSUE THREAD

**Issue by aprokop** [arborx/ArborX#71]
In ornl-cees/datatransferkit#554 I'm starting to encounter issues using ArborX in DTK because we made ArborX changes with no consideration for DTK. We need to add some form of testing to catch that up.

**Comment by aprokop** [comment]
Do we actually care about this?

**Comment by Rombur** [comment]
No, we snapshot ArborX in DTK anyway so we can just fix the problems in DTK when we update the snapshot.
