### ISSUE TITLE
Fix the warning

### ISSUE THREAD

**Issue by aprokop** [arborx/ArborX#750]
We are getting a warning
```
missing initializer for member '_GLOBAL__N__ef091c38_16_print_timers_cpp_374ae08b::Timer::duration'
```
at `print_timers.cpp:41`. But I'm don't understand what it's complaining about. The initializer for the `duration` is there.

**Comment by masterleinad** [comment]
Where do you see this warning? Is it shown in our CI?

**Comment by aprokop** [comment]
It was part of the #742 ([log](https://cloud.cees.ornl.gov/jenkins-ci/job/ArborX/job/PR-742/3/gcc/)), but was introduced in #545. However, as we don't always have all the builds (like `HIP`), we didn't catch it there.

**Comment by masterleinad** [comment]
Would using
```
arborx_dbscan_example_timers.emplace_back(label, {}, {});
```
help?

**Comment by aprokop** [comment]
Could try. I can't reproduce the warning, so it will have to be through CI.
