### ISSUE TITLE
[Question] Point search on unstructured grid

### ISSUE THREAD

**Issue by jacobmerson** [arborx/ArborX#775]
We are currently evaluating options for searching for a triangle in a (2D) unstructured grid given a point.

Is this something that ArborX currently supports? We saw that there is a Triangle geometry type defined, but no usage of triangle with BVH `query`.

**Comment by jacobmerson** [comment]
@dalg24 picking a random one is fine.

**Comment by aprokop** [comment]
@jacobmerson It would be possible to implement your use case, but it's not supported out of box. We have an example of how to do the first part (finding a triangle a point belongs to), but it is a bit convoluted (see #542). We are missing some of the functionality to properly do the second part, as we would need a) distance to the precise geometry and not the bounding box (#675), and b) function to compute a distance from a triangle to a point.

If you are interested, we could work with you to implement this. None of this is complicated, but we focused on other things.

**Comment by jacobmerson** [comment]
@cwsmith and I managed to get an example running to do the first part of this partially based on #542 , but using the standard query mechanism. Once I clean it up I will put a pull request together for a new example.

**Comment by aprokop** [comment]
This has now been implemented in ArborX. We allow computing distance to the exact geometry with APIv2, as well as provide distance point-triangle.

**Comment by jacobmerson** [comment]
Ecellent! Thanks!
