### ISSUE TITLE
Allow 2D triangles

### ISSUE THREAD

**Issue by aprokop** [arborx/ArborX#847]
`Experimental::Triangle` is hardcoded to 3D. We need to allow using 2D triangles to save memory and improve performance for problems like XGC.

**Comment by dalg24** [comment]
Template it on Point type I suppose

**Comment by aprokop** [comment]
> Template it on Point type I suppose

Why not follow other types and template on `DIM` and `FloatingPoint`?

**Comment by aprokop** [comment]
Fixed in #916.
