### ISSUE TITLE
Building against ArborX (and Kokkos) in source tree

### ISSUE THREAD

**Issue by Shihab-Shahriar** [arborx/ArborX#852]
Hi, I'm planning to build both ArborX and Kokkos in source tree. The build instructions seem to assume Kokkos is "installed". 

Right now, I have a project structure like below:

```
project
    - dep
        -- ArborX
        -- Kokkos
    - src
        -- main.cpp
    - CMakeLists.txt
```

Can you please tell me what to put in root `CMakeLists.txt` to get this to work?

**Comment by dalg24** [comment]
```CMake
cmake_minimum_required(VERSION 3.16)
project(MyProject CXX)

include(FetchContent)
FetchContent_Declare(
  Kokkos
  SOURCE_DIR ${CMAKE_CURRENT_SOURCE_DIR}/dep/kokkos
  OVERRIDE_FIND_PACKAGE
)
FetchContent_MakeAvailable(Kokkos)
FetchContent_Declare(
  ArborX
  SOURCE_DIR ${CMAKE_CURRENT_SOURCE_DIR}/dep/ArborX
)
FetchContent_MakeAvailable(ArborX)

add_executable(MyExe src/main.cpp)
target_link_libraries(MyExe ArborX::ArborX)

**Comment by aprokop** [comment]
@dalg24 Does that mean that you can provide Kokkos and ArborX options during configuration, like `-D Kokkos_ENABLE_SERIAL=ON` and `-D ArborX_ENABLE_MPI=ON`?

**Comment by dalg24** [comment]
> @dalg24 Does that mean that you can provide Kokkos and ArborX options during configuration, like `-D Kokkos_ENABLE_SERIAL=ON` and `-D ArborX_ENABLE_MPI=ON`?

Yes

**Comment by Shihab-Shahriar** [comment]
@dalg24 , thanks, it worked. Please note that I had to comment this out in `ArborX/CMakeLists.txt` to get this working:

```
if(Kokkos_ENABLE_CUDA)
   kokkos_check(OPTIONS CUDA_LAMBDA)
endif()
```

**Comment by aprokop** [comment]
According to this [reddit post](https://www.reddit.com/r/cmake/comments/10liqwm/fetchcontent_does_not_include_the_configcmake/?rdt=43486), `FetchContent` does not seem to include `*Config.cmake`, leading to the issue. Not sure why that is.

**Comment by aprokop** [comment]
With #863, the patch to comment out the check is no longer necessary when using Kokkos 4.1+.
