### ISSUE TITLE
Let DistributedTree execute user payload 

### ISSUE THREAD

**Issue by Rombur** [arborx/ArborX#86]
In the distributed case, I'd like to add a way to execute code from the user before returning the result of the query. Right now, the workflow for something like `PointSearch` in DTK is the following:
 - do a distributed search with a spatial query
 - send the points found to the target processors
 - perform some computations
 - move the results back

The goal is that the user should not need to deal with communications. At first, this will be limited to spacial predicates.  

We need to add two capabilities to the current implementation of [queryDispatch()](https://github.com/arborx/ArborX/blob/master/src/details/ArborX_DetailsDistributedSearchTreeImpl.hpp#L404-L449):
1. Execute user code
2. Move user data back to the calling processors.

The first point can be done using a functor that is called after `bottom_tree.query()` and before `communicateResultsBack()` . The second point is more complicated because we need to `serialize/deserialize` the data. The first implementation will rely on `boost::serialization` and `boost::mpi`. The object that we will communicate back will be the functor. I am not sure that returning the other like `indices`, `offset`, etc. is necessary.

**Comment by aprokop** [comment]
For spatial search this was addressed in #166, and satisfies this use case (as it needs just spatial). Nearest was not addressed as it is significantly harder. Closing the issue as the underlying problem is solved, and additional resolution for nearest is not planned for in the near future.
