### ISSUE TITLE
How to build ArborX for only CPU

### ISSUE THREAD

**Issue by dineshadepu** [arborx/ArborX#878]
Hi,

I am trying to build ArborX only on CPU. I have done the following to build it,

```
OPTIONS=(
    -D CMAKE_INSTALL_PREFIX="${KOKKOS_INSTALL_DIR}"
    -D Kokkos_ENABLE_SERIAL=ON
    -D Kokkos_ENABLE_OPENMP=ON
    -D Kokkos_ENABLE_CUDA=OFF
    )
```

Then, use `cmake` as given in the build details,
```
cmake "${OPTIONS[@]}" "${KOKKOS_SRC_DIR:-../}"
```

This is not building and giving the following error

```
adepudinesh@UoSDellLaptop (master) /home/adepudinesh/Kokkos/ArborX/build $  
|  DELL LAPTOP UoS => cmake "${OPTIONS[@]}" "${KOKKOS_SRC_DIR:-../}"
-- Setting default Kokkos CXX standard to 17
-- The CXX compiler identification is unknown
-- Detecting CXX compiler ABI info
-- Detecting CXX compiler ABI info - failed
-- Check for working CXX compiler: /home/adepudinesh/Kokkos/kokkos/bin/nvcc_wrapper
-- Check for working CXX compiler: /home/adepudinesh/Kokkos/kokkos/bin/nvcc_wrapper - broken
CMake Error at /usr/share/cmake-3.22/Modules/CMakeTestCXXCompiler.cmake:62 (message):
  The C++ compiler

    "/home/adepudinesh/Kokkos/kokkos/bin/nvcc_wrapper"

  is not able to compile a simple test program.

  It fails with the following output:

    Change Dir: /home/adepudinesh/Kokkos/ArborX/build/CMakeFiles/CMakeTmp
    
    Run Build Command(s):/usr/bin/gmake -f Makefile cmTC_67176/fast && /usr/bin/gmake  -f CMakeFiles/cmTC_67176.dir/build.make CMakeFiles/cmTC_67176.dir/build
    gmake[1]: Entering directory '/home/adepudinesh/Kokkos/ArborX/build/CMakeFiles/CMakeTmp'
    Building CXX object CMakeFiles/cmTC_67176.dir/testCXXCompiler.cxx.o
    /home/adepudinesh/Kokkos/kokkos/bin/nvcc_wrapper    -o CMakeFiles/cmTC_67176.dir/testCXXCompiler.cxx.o -c /home/adepudinesh/Kokkos/ArborX/build/CMakeFiles/CMakeTmp/testCXXCompiler.cxx
    /home/adepudinesh/Kokkos/kokkos/bin/nvcc_wrapper: line 658: nvcc: command not found
    gmake[1]: *** [CMakeFiles/cmTC_67176.dir/build.make:78: CMakeFiles/cmTC_67176.dir/testCXXCompiler.cxx.o] Error 127
    gmake[1]: Leaving directory '/home/adepudinesh/Kokkos/ArborX/build/CMakeFiles/CMakeTmp'
    gmake: *** [Makefile:127: cmTC_67176/fast] Error 2
    
    

  

  CMake will not be able to correctly generate this project.
Call Stack (most recent call first):
  CMakeLists.txt:119 (PROJECT)


-- Configuring incomplete, errors occurred!
See also "/home/adepudinesh/Kokkos/ArborX/build/CMakeFiles/CMakeOutput.log".
See also "/home/adepudinesh/Kokkos/ArborX/build/CMakeFiles/CMakeError.log".
 
```

Is there a way to only build it for `serial` and `openmp`? I have installed `kokkos` for only `serial` and `openmp` as well.

Many thanks.

**Comment by dalg24** [comment]
There is not enough information to say for sure (you don't spell out what version of Kokkos you are using and all the information about how it was configured) but you probably should not be using `nvcc_wrapper` as the CXX compiler with ArborX if CUDA is not enabled.

**Comment by dineshadepu** [comment]
Sorry, I will be more clear for future questions.

I am using the latest git repository for kokkos, which is version `4.0.1`. I have used the following commands to install `kokkos`. 

```
export KOKKOS_INSTALL_DIR=$KOKKOS_SRC_DIR/build/install
export KOKKOS_SRC_DIR=/home/adepudinesh/Kokkos/kokkos
cd kokkos

mkdir build

cd build

cmake \
-D CMAKE_BUILD_TYPE="Release" \
-D CMAKE_INSTALL_PREFIX=$KOKKOS_INSTALL_DIR \
-D Kokkos_ENABLE_OPENMP=ON \
-D Kokkos_ENABLE_SERIAL=ON \
.. ;

make install
```


To build `arborx`, I used the following commands,

```
OPTIONS=(
    -D CMAKE_INSTALL_PREFIX="${KOKKOS_INSTALL_DIR}"
    -D Kokkos_ENABLE_SERIAL=ON
    -D Kokkos_ENABLE_OPENMP=ON
    -D Kokkos_ENABLE_CUDA=OFF
	-D ARBORX_USE_CUDA_AWARE_MPI=OFF
    )
cmake "${OPTIONS[@]}" "${KOKKOS_SRC_DIR:-../}"
```

Can you please what `CXX` compiler I should change to compile `arborx` and use it?

Thank you.

**Comment by masterleinad** [comment]
I'm quite surprised why `nvcc_wrapper` is showing up for you. The configuration for `Kokkos` looks OK but you might want to add `CMAKE_CXX_COMPILER=...` to be explicit about what compiler to use.

In the configuration for `ArborX`, there is no need to specify `Kokkos` options, but you might want to set `Kokkos_ROOT=...` to the installation directory for `Kokkos` (to make sure you are picking up the correct `Kokkos` installation) and also set `CMAKE_CXX_COMPILER`. 
Also, it appears strange to use the same installation directory in the `Kokkos` and `ArborX` configurations. You likely want `CMAKE_INSTALL_PREFIX="${ARBORX_INSTALL_DIR}"` but that shouldn't have anything to do with using `nvcc_wrapper`.

**Comment by aprokop** [comment]
```
adepudinesh@UoSDellLaptop (master) /home/adepudinesh/Kokkos/ArborX/build $  
|  DELL LAPTOP UoS => cmake "${OPTIONS[@]}" "${KOKKOS_SRC_DIR:-../}"
-- Setting default Kokkos CXX standard to 17
```
I'm not sure about your directory structure, but something's weird. Did you put ArborX source inside Kokkos? I'm very confused as to why `Setting default Kokkos CXX standard to 17` appears while configuring ArborX. The only explanation I can see is that you are actually building Kokkos the second time instead of ArborX. You should use `Kokkos_ROOT` in options as @masterleinad said, and pass ArborX source directory in `cmake`.

**Comment by dineshadepu** [comment]
I made a mistake and have been following incorrect instructions. I have been installing various packages related to `cabana` over the past few days, which has led to confusion.

To rectify this, I will now proceed with the correct installation commands for arborx, which are,
```
OPTIONS=(
    -D CMAKE_INSTALL_PREFIX="${ARBORX_INSTALL_DIR}"
    -D ARBORX_ENABLE_MPI=ON
    -D Kokkos_ROOT="${KOKKOS_INSTALL_DIR}"
    -D CMAKE_CXX_COMPILER="${KOKKOS_INSTALL_DIR}/bin/nvcc_wrapper" # only for CUDA-enabled Kokkos
    -D CMAKE_CXX_EXTENSIONS=OFF # required by Kokkos
    )
cmake "${OPTIONS[@]}" "${ARBORX_DIR:-../}"
```

and close the issue once successful. Thank you @masterleinad @aprokop @dalg24 for your valuable inputs :)
