### ISSUE TITLE
OneDPL added sort_by_key

### ISSUE THREAD

**Issue by aprokop** [arborx/ArborX#926]
It was recently added in oneapi-src/oneDPL#859. Should probably switch to using that and avoid zipping stuff together as we do right now: 

https://github.com/arborx/ArborX/blob/d05083f6f8d908351ddf7fe5a66884458f6c781f/src/kokkos_ext/ArborX_DetailsKokkosExtSort.hpp#L173C1-L179

The question is whether its performance is any better or worse than what we have right now.

**Comment by masterleinad** [comment]
At the moment it is also using `zip_iterator`, https://github.com/oneapi-src/oneDPL/blob/8528820d414921ce04169157e212d5bc6421ba1e/include/oneapi/dpl/pstl/algorithm_impl.h#L2375-L2411.

**Comment by aprokop** [comment]
@masterleinad So it would be fine to switch to their version then, and move that complexity out of our code. When they improve things (which they should, 'cause their performance is really subpar to CUDA), we'll get automatic benefit.
